// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateScenarioReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateScenarioResp struct {
	Id string `json:"id"`
}

type CreateSessionReq struct {
	UserProfileId string `json:"user_profile_id"`
	ScenarioId    string `json:"scenario_id"`
}

type CreateSessionResp struct {
	SessionId string `json:"session_id"`
}

type CreateUserProfileReq struct {
	EnglishLevel   string `json:"english_level"`
	LearningTarget string `json:"learning_target"`
}

type CreateUserProfileResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type DeleteSessionReq struct {
	SessionId string `path:"session_id"`
}

type DeleteSessionResp struct {
	Success bool `json:"success"`
}

type GenerateUploadUrlReq struct {
	Filename string `json:"filename"`
}

type GenerateUploadUrlResp struct {
	UploadUrl string `json:"upload_url"`
	ObjectKey string `json:"object_key"`
}

type GetSessionDetailReq struct {
	SessionId string `path:"session_id"`
}

type GetSessionDetailResp struct {
	SessionId    string `json:"session_id"`
	ScenarioName string `json:"scenario_name"`
	Transcript   string `json:"transcript"`
	OverallScore int32  `json:"overall_score"`
	Commentary   string `json:"commentary"`
}

type GetUserInfoResp struct {
	Id              string `json:"id"`
	Username        string `json:"username"`
	Email           string `json:"email"`
	DailyFreeTokens uint32 `json:"daily_free_tokens"`
	RechargeTokens  uint64 `json:"recharge_tokens"`
}

type GetUserProfileReq struct {
	Id string `path:"id"`
}

type GetUserProfileResp struct {
	Id             string `json:"id"`
	EnglishLevel   string `json:"english_level"`
	LearningTarget string `json:"learning_target"`
	CreatedAt      int64  `json:"created_at"`
}

type ListScenariosResp struct {
	Scenarios []ScenarioItem `json:"scenarios"`
}

type ListSessionsResp struct {
	Sessions []PracticeSession `json:"sessions"`
}

type ListUserProfilesResp struct {
	Profiles []UserProfileItem `json:"profiles"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

type PracticeSession struct {
	SessionId    string `json:"session_id"`
	ScenarioName string `json:"scenario_name"`
	Status       string `json:"status"`
	CreatedAt    int64  `json:"created_at"`
	OverallScore int32  `json:"overall_score"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id string `json:"id"`
}

type ScenarioItem struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatorId   string `json:"creator_id"`
	CreatedAt   int64  `json:"created_at"`
}

type UserProfileItem struct {
	Id             string `json:"id"`
	EnglishLevel   string `json:"english_level"`
	LearningTarget string `json:"learning_target"`
	CreatedAt      int64  `json:"created_at"`
}
