// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: core.proto

package coreclient

import (
	"context"

	"ai_interview/rpc/core/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddDialogueReq               = core.AddDialogueReq
	AddDialogueResp              = core.AddDialogueResp
	CreateScenarioReq            = core.CreateScenarioReq
	CreateScenarioResp           = core.CreateScenarioResp
	CreateSessionReq             = core.CreateSessionReq
	CreateSessionResp            = core.CreateSessionResp
	CreateUserProfileReq         = core.CreateUserProfileReq
	CreateUserProfileResp        = core.CreateUserProfileResp
	DeleteSessionReq             = core.DeleteSessionReq
	DeleteSessionResp            = core.DeleteSessionResp
	GenerateUploadUrlReq         = core.GenerateUploadUrlReq
	GenerateUploadUrlResp        = core.GenerateUploadUrlResp
	GetPracticeContextReq        = core.GetPracticeContextReq
	GetPracticeContextResp       = core.GetPracticeContextResp
	GetScenarioReq               = core.GetScenarioReq
	GetScenarioResp              = core.GetScenarioResp
	GetSessionDetailReq          = core.GetSessionDetailReq
	GetSessionDetailResp         = core.GetSessionDetailResp
	GetUserProfileReq            = core.GetUserProfileReq
	GetUserProfileResp           = core.GetUserProfileResp
	ListSessionsReq              = core.ListSessionsReq
	ListSessionsResp             = core.ListSessionsResp
	SessionItem                  = core.SessionItem
	UpdateDialogueEvaluationReq  = core.UpdateDialogueEvaluationReq
	UpdateDialogueEvaluationResp = core.UpdateDialogueEvaluationResp
	UpdateSessionStatusReq       = core.UpdateSessionStatusReq
	UpdateSessionStatusResp      = core.UpdateSessionStatusResp

	Core interface {
		// User Profile & OSS
		GenerateUploadUrl(ctx context.Context, in *GenerateUploadUrlReq, opts ...grpc.CallOption) (*GenerateUploadUrlResp, error)
		CreateUserProfile(ctx context.Context, in *CreateUserProfileReq, opts ...grpc.CallOption) (*CreateUserProfileResp, error)
		GetUserProfile(ctx context.Context, in *GetUserProfileReq, opts ...grpc.CallOption) (*GetUserProfileResp, error)
		// Scenarios
		CreateScenario(ctx context.Context, in *CreateScenarioReq, opts ...grpc.CallOption) (*CreateScenarioResp, error)
		GetScenario(ctx context.Context, in *GetScenarioReq, opts ...grpc.CallOption) (*GetScenarioResp, error)
		// Practice Sessions
		CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error)
		UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error)
		// Dialogues
		AddDialogue(ctx context.Context, in *AddDialogueReq, opts ...grpc.CallOption) (*AddDialogueResp, error)
		UpdateDialogueEvaluation(ctx context.Context, in *UpdateDialogueEvaluationReq, opts ...grpc.CallOption) (*UpdateDialogueEvaluationResp, error)
		// 上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
		GetPracticeContext(ctx context.Context, in *GetPracticeContextReq, opts ...grpc.CallOption) (*GetPracticeContextResp, error)
		// 列表与详情
		ListSessions(ctx context.Context, in *ListSessionsReq, opts ...grpc.CallOption) (*ListSessionsResp, error)
		GetSessionDetail(ctx context.Context, in *GetSessionDetailReq, opts ...grpc.CallOption) (*GetSessionDetailResp, error)
		DeleteSession(ctx context.Context, in *DeleteSessionReq, opts ...grpc.CallOption) (*DeleteSessionResp, error)
	}

	defaultCore struct {
		cli zrpc.Client
	}
)

func NewCore(cli zrpc.Client) Core {
	return &defaultCore{
		cli: cli,
	}
}

// User Profile & OSS
func (m *defaultCore) GenerateUploadUrl(ctx context.Context, in *GenerateUploadUrlReq, opts ...grpc.CallOption) (*GenerateUploadUrlResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GenerateUploadUrl(ctx, in, opts...)
}

func (m *defaultCore) CreateUserProfile(ctx context.Context, in *CreateUserProfileReq, opts ...grpc.CallOption) (*CreateUserProfileResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateUserProfile(ctx, in, opts...)
}

func (m *defaultCore) GetUserProfile(ctx context.Context, in *GetUserProfileReq, opts ...grpc.CallOption) (*GetUserProfileResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetUserProfile(ctx, in, opts...)
}

// Scenarios
func (m *defaultCore) CreateScenario(ctx context.Context, in *CreateScenarioReq, opts ...grpc.CallOption) (*CreateScenarioResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateScenario(ctx, in, opts...)
}

func (m *defaultCore) GetScenario(ctx context.Context, in *GetScenarioReq, opts ...grpc.CallOption) (*GetScenarioResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetScenario(ctx, in, opts...)
}

// Practice Sessions
func (m *defaultCore) CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateSession(ctx, in, opts...)
}

func (m *defaultCore) UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UpdateSessionStatus(ctx, in, opts...)
}

// Dialogues
func (m *defaultCore) AddDialogue(ctx context.Context, in *AddDialogueReq, opts ...grpc.CallOption) (*AddDialogueResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.AddDialogue(ctx, in, opts...)
}

func (m *defaultCore) UpdateDialogueEvaluation(ctx context.Context, in *UpdateDialogueEvaluationReq, opts ...grpc.CallOption) (*UpdateDialogueEvaluationResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UpdateDialogueEvaluation(ctx, in, opts...)
}

// 上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
func (m *defaultCore) GetPracticeContext(ctx context.Context, in *GetPracticeContextReq, opts ...grpc.CallOption) (*GetPracticeContextResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetPracticeContext(ctx, in, opts...)
}

// 列表与详情
func (m *defaultCore) ListSessions(ctx context.Context, in *ListSessionsReq, opts ...grpc.CallOption) (*ListSessionsResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ListSessions(ctx, in, opts...)
}

func (m *defaultCore) GetSessionDetail(ctx context.Context, in *GetSessionDetailReq, opts ...grpc.CallOption) (*GetSessionDetailResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetSessionDetail(ctx, in, opts...)
}

func (m *defaultCore) DeleteSession(ctx context.Context, in *DeleteSessionReq, opts ...grpc.CallOption) (*DeleteSessionResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.DeleteSession(ctx, in, opts...)
}
