// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: core.proto

package coreclient

import (
	"context"

	"ai_interview/rpc/core/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddDialogueReq               = core.AddDialogueReq
	AddDialogueResp              = core.AddDialogueResp
	CreateJobProfileReq          = core.CreateJobProfileReq
	CreateJobProfileResp         = core.CreateJobProfileResp
	CreateResumeReq              = core.CreateResumeReq
	CreateResumeResp             = core.CreateResumeResp
	CreateSessionReq             = core.CreateSessionReq
	CreateSessionResp            = core.CreateSessionResp
	DeleteSessionReq             = core.DeleteSessionReq
	DeleteSessionResp            = core.DeleteSessionResp
	GenerateUploadUrlReq         = core.GenerateUploadUrlReq
	GenerateUploadUrlResp        = core.GenerateUploadUrlResp
	GetInterviewContextReq       = core.GetInterviewContextReq
	GetInterviewContextResp      = core.GetInterviewContextResp
	GetJobProfileReq             = core.GetJobProfileReq
	GetJobProfileResp            = core.GetJobProfileResp
	GetResumeReq                 = core.GetResumeReq
	GetResumeResp                = core.GetResumeResp
	GetSessionDetailReq          = core.GetSessionDetailReq
	GetSessionDetailResp         = core.GetSessionDetailResp
	ListSessionsReq              = core.ListSessionsReq
	ListSessionsResp             = core.ListSessionsResp
	SessionItem                  = core.SessionItem
	UpdateDialogueEvaluationReq  = core.UpdateDialogueEvaluationReq
	UpdateDialogueEvaluationResp = core.UpdateDialogueEvaluationResp
	UpdateSessionStatusReq       = core.UpdateSessionStatusReq
	UpdateSessionStatusResp      = core.UpdateSessionStatusResp

	Core interface {
		// Resume & OSS
		GenerateUploadUrl(ctx context.Context, in *GenerateUploadUrlReq, opts ...grpc.CallOption) (*GenerateUploadUrlResp, error)
		CreateResume(ctx context.Context, in *CreateResumeReq, opts ...grpc.CallOption) (*CreateResumeResp, error)
		GetResume(ctx context.Context, in *GetResumeReq, opts ...grpc.CallOption) (*GetResumeResp, error)
		// Job Profiles
		CreateJobProfile(ctx context.Context, in *CreateJobProfileReq, opts ...grpc.CallOption) (*CreateJobProfileResp, error)
		GetJobProfile(ctx context.Context, in *GetJobProfileReq, opts ...grpc.CallOption) (*GetJobProfileResp, error)
		// Interview Sessions
		CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error)
		UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error)
		// Interview Dialogues
		AddDialogue(ctx context.Context, in *AddDialogueReq, opts ...grpc.CallOption) (*AddDialogueResp, error)
		UpdateDialogueEvaluation(ctx context.Context, in *UpdateDialogueEvaluationReq, opts ...grpc.CallOption) (*UpdateDialogueEvaluationResp, error)
		// 面试上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
		GetInterviewContext(ctx context.Context, in *GetInterviewContextReq, opts ...grpc.CallOption) (*GetInterviewContextResp, error)
		// 面试列表与详情
		ListSessions(ctx context.Context, in *ListSessionsReq, opts ...grpc.CallOption) (*ListSessionsResp, error)
		GetSessionDetail(ctx context.Context, in *GetSessionDetailReq, opts ...grpc.CallOption) (*GetSessionDetailResp, error)
		DeleteSession(ctx context.Context, in *DeleteSessionReq, opts ...grpc.CallOption) (*DeleteSessionResp, error)
	}

	defaultCore struct {
		cli zrpc.Client
	}
)

func NewCore(cli zrpc.Client) Core {
	return &defaultCore{
		cli: cli,
	}
}

// Resume & OSS
func (m *defaultCore) GenerateUploadUrl(ctx context.Context, in *GenerateUploadUrlReq, opts ...grpc.CallOption) (*GenerateUploadUrlResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GenerateUploadUrl(ctx, in, opts...)
}

func (m *defaultCore) CreateResume(ctx context.Context, in *CreateResumeReq, opts ...grpc.CallOption) (*CreateResumeResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateResume(ctx, in, opts...)
}

func (m *defaultCore) GetResume(ctx context.Context, in *GetResumeReq, opts ...grpc.CallOption) (*GetResumeResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetResume(ctx, in, opts...)
}

// Job Profiles
func (m *defaultCore) CreateJobProfile(ctx context.Context, in *CreateJobProfileReq, opts ...grpc.CallOption) (*CreateJobProfileResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateJobProfile(ctx, in, opts...)
}

func (m *defaultCore) GetJobProfile(ctx context.Context, in *GetJobProfileReq, opts ...grpc.CallOption) (*GetJobProfileResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetJobProfile(ctx, in, opts...)
}

// Interview Sessions
func (m *defaultCore) CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.CreateSession(ctx, in, opts...)
}

func (m *defaultCore) UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UpdateSessionStatus(ctx, in, opts...)
}

// Interview Dialogues
func (m *defaultCore) AddDialogue(ctx context.Context, in *AddDialogueReq, opts ...grpc.CallOption) (*AddDialogueResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.AddDialogue(ctx, in, opts...)
}

func (m *defaultCore) UpdateDialogueEvaluation(ctx context.Context, in *UpdateDialogueEvaluationReq, opts ...grpc.CallOption) (*UpdateDialogueEvaluationResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.UpdateDialogueEvaluation(ctx, in, opts...)
}

// 面试上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
func (m *defaultCore) GetInterviewContext(ctx context.Context, in *GetInterviewContextReq, opts ...grpc.CallOption) (*GetInterviewContextResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetInterviewContext(ctx, in, opts...)
}

// 面试列表与详情
func (m *defaultCore) ListSessions(ctx context.Context, in *ListSessionsReq, opts ...grpc.CallOption) (*ListSessionsResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.ListSessions(ctx, in, opts...)
}

func (m *defaultCore) GetSessionDetail(ctx context.Context, in *GetSessionDetailReq, opts ...grpc.CallOption) (*GetSessionDetailResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.GetSessionDetail(ctx, in, opts...)
}

func (m *defaultCore) DeleteSession(ctx context.Context, in *DeleteSessionReq, opts ...grpc.CallOption) (*DeleteSessionResp, error) {
	client := core.NewCoreClient(m.cli.Conn())
	return client.DeleteSession(ctx, in, opts...)
}
