// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: rpc/ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseResumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawText       string                 `protobuf:"bytes,1,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResumeReq) Reset() {
	*x = ParseResumeReq{}
	mi := &file_rpc_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResumeReq) ProtoMessage() {}

func (x *ParseResumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResumeReq.ProtoReflect.Descriptor instead.
func (*ParseResumeReq) Descriptor() ([]byte, []int) {
	return file_rpc_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ParseResumeReq) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

type ParseResumeResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StructuredJson string                 `protobuf:"bytes,1,opt,name=structured_json,json=structuredJson,proto3" json:"structured_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseResumeResp) Reset() {
	*x = ParseResumeResp{}
	mi := &file_rpc_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResumeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResumeResp) ProtoMessage() {}

func (x *ParseResumeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResumeResp.ProtoReflect.Descriptor instead.
func (*ParseResumeResp) Descriptor() ([]byte, []int) {
	return file_rpc_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResumeResp) GetStructuredJson() string {
	if x != nil {
		return x.StructuredJson
	}
	return ""
}

type GetAiSuggestionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAiSuggestionReq) Reset() {
	*x = GetAiSuggestionReq{}
	mi := &file_rpc_ai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAiSuggestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAiSuggestionReq) ProtoMessage() {}

func (x *GetAiSuggestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAiSuggestionReq.ProtoReflect.Descriptor instead.
func (*GetAiSuggestionReq) Descriptor() ([]byte, []int) {
	return file_rpc_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GetAiSuggestionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetAiSuggestionReq) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type GetAiSuggestionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestion    string                 `protobuf:"bytes,1,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAiSuggestionResp) Reset() {
	*x = GetAiSuggestionResp{}
	mi := &file_rpc_ai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAiSuggestionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAiSuggestionResp) ProtoMessage() {}

func (x *GetAiSuggestionResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAiSuggestionResp.ProtoReflect.Descriptor instead.
func (*GetAiSuggestionResp) Descriptor() ([]byte, []int) {
	return file_rpc_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GetAiSuggestionResp) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

type GetAiCommentaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	AudioContent  []byte                 `protobuf:"bytes,3,opt,name=audio_content,json=audioContent,proto3" json:"audio_content,omitempty"` // 用户回答的完整 WAV 音频内容字节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAiCommentaryReq) Reset() {
	*x = GetAiCommentaryReq{}
	mi := &file_rpc_ai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAiCommentaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAiCommentaryReq) ProtoMessage() {}

func (x *GetAiCommentaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAiCommentaryReq.ProtoReflect.Descriptor instead.
func (*GetAiCommentaryReq) Descriptor() ([]byte, []int) {
	return file_rpc_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *GetAiCommentaryReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetAiCommentaryReq) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *GetAiCommentaryReq) GetAudioContent() []byte {
	if x != nil {
		return x.AudioContent
	}
	return nil
}

type GetAiCommentaryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commentary    string                 `protobuf:"bytes,1,opt,name=commentary,proto3" json:"commentary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAiCommentaryResp) Reset() {
	*x = GetAiCommentaryResp{}
	mi := &file_rpc_ai_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAiCommentaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAiCommentaryResp) ProtoMessage() {}

func (x *GetAiCommentaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ai_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAiCommentaryResp.ProtoReflect.Descriptor instead.
func (*GetAiCommentaryResp) Descriptor() ([]byte, []int) {
	return file_rpc_ai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *GetAiCommentaryResp) GetCommentary() string {
	if x != nil {
		return x.Commentary
	}
	return ""
}

var File_rpc_ai_ai_proto protoreflect.FileDescriptor

const file_rpc_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\x0frpc/ai/ai.proto\x12\x02ai\"+\n" +
	"\x0eParseResumeReq\x12\x19\n" +
	"\braw_text\x18\x01 \x01(\tR\arawText\":\n" +
	"\x0fParseResumeResp\x12'\n" +
	"\x0fstructured_json\x18\x01 \x01(\tR\x0estructuredJson\"M\n" +
	"\x12GetAiSuggestionReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\"5\n" +
	"\x13GetAiSuggestionResp\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x01 \x01(\tR\n" +
	"suggestion\"r\n" +
	"\x12GetAiCommentaryReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12#\n" +
	"\raudio_content\x18\x03 \x01(\fR\faudioContent\"5\n" +
	"\x13GetAiCommentaryResp\x12\x1e\n" +
	"\n" +
	"commentary\x18\x01 \x01(\tR\n" +
	"commentary2\xc4\x01\n" +
	"\x02Ai\x126\n" +
	"\vParseResume\x12\x12.ai.ParseResumeReq\x1a\x13.ai.ParseResumeResp\x12B\n" +
	"\x0fGetAiSuggestion\x12\x16.ai.GetAiSuggestionReq\x1a\x17.ai.GetAiSuggestionResp\x12B\n" +
	"\x0fGetAiCommentary\x12\x16.ai.GetAiCommentaryReq\x1a\x17.ai.GetAiCommentaryRespB\x06Z\x04./aib\x06proto3"

var (
	file_rpc_ai_ai_proto_rawDescOnce sync.Once
	file_rpc_ai_ai_proto_rawDescData []byte
)

func file_rpc_ai_ai_proto_rawDescGZIP() []byte {
	file_rpc_ai_ai_proto_rawDescOnce.Do(func() {
		file_rpc_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_ai_ai_proto_rawDesc), len(file_rpc_ai_ai_proto_rawDesc)))
	})
	return file_rpc_ai_ai_proto_rawDescData
}

var file_rpc_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_ai_ai_proto_goTypes = []any{
	(*ParseResumeReq)(nil),      // 0: ai.ParseResumeReq
	(*ParseResumeResp)(nil),     // 1: ai.ParseResumeResp
	(*GetAiSuggestionReq)(nil),  // 2: ai.GetAiSuggestionReq
	(*GetAiSuggestionResp)(nil), // 3: ai.GetAiSuggestionResp
	(*GetAiCommentaryReq)(nil),  // 4: ai.GetAiCommentaryReq
	(*GetAiCommentaryResp)(nil), // 5: ai.GetAiCommentaryResp
}
var file_rpc_ai_ai_proto_depIdxs = []int32{
	0, // 0: ai.Ai.ParseResume:input_type -> ai.ParseResumeReq
	2, // 1: ai.Ai.GetAiSuggestion:input_type -> ai.GetAiSuggestionReq
	4, // 2: ai.Ai.GetAiCommentary:input_type -> ai.GetAiCommentaryReq
	1, // 3: ai.Ai.ParseResume:output_type -> ai.ParseResumeResp
	3, // 4: ai.Ai.GetAiSuggestion:output_type -> ai.GetAiSuggestionResp
	5, // 5: ai.Ai.GetAiCommentary:output_type -> ai.GetAiCommentaryResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_ai_ai_proto_init() }
func file_rpc_ai_ai_proto_init() {
	if File_rpc_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_ai_ai_proto_rawDesc), len(file_rpc_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_ai_ai_proto_goTypes,
		DependencyIndexes: file_rpc_ai_ai_proto_depIdxs,
		MessageInfos:      file_rpc_ai_ai_proto_msgTypes,
	}.Build()
	File_rpc_ai_ai_proto = out.File
	file_rpc_ai_ai_proto_goTypes = nil
	file_rpc_ai_ai_proto_depIdxs = nil
}
