// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: rpc/ai/ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ai_ParseResume_FullMethodName     = "/ai.Ai/ParseResume"
	Ai_GetAiSuggestion_FullMethodName = "/ai.Ai/GetAiSuggestion"
	Ai_GetAiCommentary_FullMethodName = "/ai.Ai/GetAiCommentary"
)

// AiClient is the client API for Ai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiClient interface {
	ParseResume(ctx context.Context, in *ParseResumeReq, opts ...grpc.CallOption) (*ParseResumeResp, error)
	GetAiSuggestion(ctx context.Context, in *GetAiSuggestionReq, opts ...grpc.CallOption) (*GetAiSuggestionResp, error)
	GetAiCommentary(ctx context.Context, in *GetAiCommentaryReq, opts ...grpc.CallOption) (*GetAiCommentaryResp, error)
}

type aiClient struct {
	cc grpc.ClientConnInterface
}

func NewAiClient(cc grpc.ClientConnInterface) AiClient {
	return &aiClient{cc}
}

func (c *aiClient) ParseResume(ctx context.Context, in *ParseResumeReq, opts ...grpc.CallOption) (*ParseResumeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResumeResp)
	err := c.cc.Invoke(ctx, Ai_ParseResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetAiSuggestion(ctx context.Context, in *GetAiSuggestionReq, opts ...grpc.CallOption) (*GetAiSuggestionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAiSuggestionResp)
	err := c.cc.Invoke(ctx, Ai_GetAiSuggestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetAiCommentary(ctx context.Context, in *GetAiCommentaryReq, opts ...grpc.CallOption) (*GetAiCommentaryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAiCommentaryResp)
	err := c.cc.Invoke(ctx, Ai_GetAiCommentary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServer is the server API for Ai service.
// All implementations must embed UnimplementedAiServer
// for forward compatibility.
type AiServer interface {
	ParseResume(context.Context, *ParseResumeReq) (*ParseResumeResp, error)
	GetAiSuggestion(context.Context, *GetAiSuggestionReq) (*GetAiSuggestionResp, error)
	GetAiCommentary(context.Context, *GetAiCommentaryReq) (*GetAiCommentaryResp, error)
	mustEmbedUnimplementedAiServer()
}

// UnimplementedAiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServer struct{}

func (UnimplementedAiServer) ParseResume(context.Context, *ParseResumeReq) (*ParseResumeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseResume not implemented")
}
func (UnimplementedAiServer) GetAiSuggestion(context.Context, *GetAiSuggestionReq) (*GetAiSuggestionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAiSuggestion not implemented")
}
func (UnimplementedAiServer) GetAiCommentary(context.Context, *GetAiCommentaryReq) (*GetAiCommentaryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAiCommentary not implemented")
}
func (UnimplementedAiServer) mustEmbedUnimplementedAiServer() {}
func (UnimplementedAiServer) testEmbeddedByValue()            {}

// UnsafeAiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServer will
// result in compilation errors.
type UnsafeAiServer interface {
	mustEmbedUnimplementedAiServer()
}

func RegisterAiServer(s grpc.ServiceRegistrar, srv AiServer) {
	// If the following call panics, it indicates UnimplementedAiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ai_ServiceDesc, srv)
}

func _Ai_ParseResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseResumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).ParseResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_ParseResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).ParseResume(ctx, req.(*ParseResumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetAiSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAiSuggestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetAiSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetAiSuggestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetAiSuggestion(ctx, req.(*GetAiSuggestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetAiCommentary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAiCommentaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetAiCommentary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetAiCommentary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetAiCommentary(ctx, req.(*GetAiCommentaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ai_ServiceDesc is the grpc.ServiceDesc for Ai service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ai_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.Ai",
	HandlerType: (*AiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseResume",
			Handler:    _Ai_ParseResume_Handler,
		},
		{
			MethodName: "GetAiSuggestion",
			Handler:    _Ai_GetAiSuggestion_Handler,
		},
		{
			MethodName: "GetAiCommentary",
			Handler:    _Ai_GetAiCommentary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/ai/ai.proto",
}
