// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userclient

import (
	"context"

	"ai_interview/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductTokenReq  = user.DeductTokenReq
	DeductTokenResp = user.DeductTokenResp
	GetUserInfoReq  = user.GetUserInfoReq
	GetUserInfoResp = user.GetUserInfoResp
	LoginReq        = user.LoginReq
	LoginResp       = user.LoginResp
	RegisterReq     = user.RegisterReq
	RegisterResp    = user.RegisterResp

	User interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		DeductToken(ctx context.Context, in *DeductTokenReq, opts ...grpc.CallOption) (*DeductTokenResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) DeductToken(ctx context.Context, in *DeductTokenReq, opts ...grpc.CallOption) (*DeductTokenResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeductToken(ctx, in, opts...)
}
