// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package server

import (
	"context"

	"ai_companion/rpc/ai/ai"
	"ai_companion/rpc/ai/internal/logic"
	"ai_companion/rpc/ai/internal/svc"
)

type AiServer struct {
	svcCtx *svc.ServiceContext
	ai.UnimplementedAiServer
}

func NewAiServer(svcCtx *svc.ServiceContext) *AiServer {
	return &AiServer{
		svcCtx: svcCtx,
	}
}

func (s *AiServer) ParseResume(ctx context.Context, in *ai.ParseResumeReq) (*ai.ParseResumeResp, error) {
	l := logic.NewParseResumeLogic(ctx, s.svcCtx)
	return l.ParseResume(in)
}

func (s *AiServer) GetAiSuggestion(ctx context.Context, in *ai.GetAiSuggestionReq) (*ai.GetAiSuggestionResp, error) {
	l := logic.NewGetAiSuggestionLogic(ctx, s.svcCtx)
	return l.GetAiSuggestion(in)
}

func (s *AiServer) GetAiCommentary(ctx context.Context, in *ai.GetAiCommentaryReq) (*ai.GetAiCommentaryResp, error) {
	l := logic.NewGetAiCommentaryLogic(ctx, s.svcCtx)
	return l.GetAiCommentary(in)
}
