// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dialoguesFieldNames          = builder.RawFieldNames(&Dialogues{})
	dialoguesRows                = strings.Join(dialoguesFieldNames, ",")
	dialoguesRowsExpectAutoSet   = strings.Join(stringx.Remove(dialoguesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dialoguesRowsWithPlaceHolder = strings.Join(stringx.Remove(dialoguesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDialoguesIdPrefix = "cache:dialogues:id:"
)

type (
	dialoguesModel interface {
		Insert(ctx context.Context, data *Dialogues) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Dialogues, error)
		Update(ctx context.Context, data *Dialogues) error
		Delete(ctx context.Context, id string) error
	}

	defaultDialoguesModel struct {
		sqlc.CachedConn
		table string
	}

	Dialogues struct {
		Id                string         `db:"id"`                  // 唯一标识 (UUID)
		PracticeSessionId string         `db:"practice_session_id"` // 练习会话ID
		Role              string         `db:"role"`                // 角色 (保持与老代码兼容使用这三种枚举)
		AudioUrl          sql.NullString `db:"audio_url"`           // 录音音频URL
		Content           string         `db:"content"`             // 对话文本内容
		Evaluation        sql.NullString `db:"evaluation"`          // AI对本轮回答的评估打分(JSON格式文本)
		CreatedAt         time.Time      `db:"created_at"`          // 创建时间
	}
)

func newDialoguesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDialoguesModel {
	return &defaultDialoguesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`dialogues`",
	}
}

func (m *defaultDialoguesModel) Delete(ctx context.Context, id string) error {
	dialoguesIdKey := fmt.Sprintf("%s%v", cacheDialoguesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, dialoguesIdKey)
	return err
}

func (m *defaultDialoguesModel) FindOne(ctx context.Context, id string) (*Dialogues, error) {
	dialoguesIdKey := fmt.Sprintf("%s%v", cacheDialoguesIdPrefix, id)
	var resp Dialogues
	err := m.QueryRowCtx(ctx, &resp, dialoguesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dialoguesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDialoguesModel) Insert(ctx context.Context, data *Dialogues) (sql.Result, error) {
	dialoguesIdKey := fmt.Sprintf("%s%v", cacheDialoguesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, dialoguesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.PracticeSessionId, data.Role, data.AudioUrl, data.Content, data.Evaluation)
	}, dialoguesIdKey)
	return ret, err
}

func (m *defaultDialoguesModel) Update(ctx context.Context, data *Dialogues) error {
	dialoguesIdKey := fmt.Sprintf("%s%v", cacheDialoguesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dialoguesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PracticeSessionId, data.Role, data.AudioUrl, data.Content, data.Evaluation, data.Id)
	}, dialoguesIdKey)
	return err
}

func (m *defaultDialoguesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDialoguesIdPrefix, primary)
}

func (m *defaultDialoguesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dialoguesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDialoguesModel) tableName() string {
	return m.table
}
