// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	interviewSessionsFieldNames          = builder.RawFieldNames(&InterviewSessions{})
	interviewSessionsRows                = strings.Join(interviewSessionsFieldNames, ",")
	interviewSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(interviewSessionsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	interviewSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(interviewSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheInterviewSessionsIdPrefix = "cache:interviewSessions:id:"
)

type (
	interviewSessionsModel interface {
		Insert(ctx context.Context, data *InterviewSessions) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*InterviewSessions, error)
		Update(ctx context.Context, data *InterviewSessions) error
		Delete(ctx context.Context, id string) error
	}

	defaultInterviewSessionsModel struct {
		sqlc.CachedConn
		table string
	}

	InterviewSessions struct {
		Id               string         `db:"id"`                // 唯一标识 (UUID)
		UserId           string         `db:"user_id"`           // 用户ID
		ResumeId         string         `db:"resume_id"`         // 简历ID
		JobProfileId     string         `db:"job_profile_id"`    // 岗位ID
		Status           string         `db:"status"`            // 状态
		EvaluationReport sql.NullString `db:"evaluation_report"` // 面试评估报告
		CreatedAt        time.Time      `db:"created_at"`        // 创建时间
		UpdatedAt        time.Time      `db:"updated_at"`        // 更新时间
	}
)

func newInterviewSessionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInterviewSessionsModel {
	return &defaultInterviewSessionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`interview_sessions`",
	}
}

func (m *defaultInterviewSessionsModel) Delete(ctx context.Context, id string) error {
	interviewSessionsIdKey := fmt.Sprintf("%s%v", cacheInterviewSessionsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, interviewSessionsIdKey)
	return err
}

func (m *defaultInterviewSessionsModel) FindOne(ctx context.Context, id string) (*InterviewSessions, error) {
	interviewSessionsIdKey := fmt.Sprintf("%s%v", cacheInterviewSessionsIdPrefix, id)
	var resp InterviewSessions
	err := m.QueryRowCtx(ctx, &resp, interviewSessionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interviewSessionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInterviewSessionsModel) Insert(ctx context.Context, data *InterviewSessions) (sql.Result, error) {
	interviewSessionsIdKey := fmt.Sprintf("%s%v", cacheInterviewSessionsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, interviewSessionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.ResumeId, data.JobProfileId, data.Status, data.EvaluationReport)
	}, interviewSessionsIdKey)
	return ret, err
}

func (m *defaultInterviewSessionsModel) Update(ctx context.Context, data *InterviewSessions) error {
	interviewSessionsIdKey := fmt.Sprintf("%s%v", cacheInterviewSessionsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, interviewSessionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.ResumeId, data.JobProfileId, data.Status, data.EvaluationReport, data.Id)
	}, interviewSessionsIdKey)
	return err
}

func (m *defaultInterviewSessionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheInterviewSessionsIdPrefix, primary)
}

func (m *defaultInterviewSessionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interviewSessionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInterviewSessionsModel) tableName() string {
	return m.table
}
