// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	interviewDialoguesFieldNames          = builder.RawFieldNames(&InterviewDialogues{})
	interviewDialoguesRows                = strings.Join(interviewDialoguesFieldNames, ",")
	interviewDialoguesRowsExpectAutoSet   = strings.Join(stringx.Remove(interviewDialoguesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	interviewDialoguesRowsWithPlaceHolder = strings.Join(stringx.Remove(interviewDialoguesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheInterviewDialoguesIdPrefix = "cache:interviewDialogues:id:"
)

type (
	interviewDialoguesModel interface {
		Insert(ctx context.Context, data *InterviewDialogues) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*InterviewDialogues, error)
		Update(ctx context.Context, data *InterviewDialogues) error
		Delete(ctx context.Context, id string) error
	}

	defaultInterviewDialoguesModel struct {
		sqlc.CachedConn
		table string
	}

	InterviewDialogues struct {
		Id                 string         `db:"id"`                   // 唯一标识 (UUID)
		InterviewSessionId string         `db:"interview_session_id"` // 面试会话ID
		Role               string         `db:"role"`                 // 角色
		AudioUrl           sql.NullString `db:"audio_url"`            // 音频URL(optional)
		Content            string         `db:"content"`              // 对话内容
		Evaluation         sql.NullString `db:"evaluation"`           // 此轮回答的 AI 评估报告 (JSON 格式文本)
		CreatedAt          time.Time      `db:"created_at"`           // 创建时间
	}
)

func newInterviewDialoguesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInterviewDialoguesModel {
	return &defaultInterviewDialoguesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`interview_dialogues`",
	}
}

func (m *defaultInterviewDialoguesModel) Delete(ctx context.Context, id string) error {
	interviewDialoguesIdKey := fmt.Sprintf("%s%v", cacheInterviewDialoguesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, interviewDialoguesIdKey)
	return err
}

func (m *defaultInterviewDialoguesModel) FindOne(ctx context.Context, id string) (*InterviewDialogues, error) {
	interviewDialoguesIdKey := fmt.Sprintf("%s%v", cacheInterviewDialoguesIdPrefix, id)
	var resp InterviewDialogues
	err := m.QueryRowCtx(ctx, &resp, interviewDialoguesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interviewDialoguesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInterviewDialoguesModel) Insert(ctx context.Context, data *InterviewDialogues) (sql.Result, error) {
	interviewDialoguesIdKey := fmt.Sprintf("%s%v", cacheInterviewDialoguesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, interviewDialoguesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.InterviewSessionId, data.Role, data.AudioUrl, data.Content, data.Evaluation)
	}, interviewDialoguesIdKey)
	return ret, err
}

func (m *defaultInterviewDialoguesModel) Update(ctx context.Context, data *InterviewDialogues) error {
	interviewDialoguesIdKey := fmt.Sprintf("%s%v", cacheInterviewDialoguesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, interviewDialoguesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.InterviewSessionId, data.Role, data.AudioUrl, data.Content, data.Evaluation, data.Id)
	}, interviewDialoguesIdKey)
	return err
}

func (m *defaultInterviewDialoguesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheInterviewDialoguesIdPrefix, primary)
}

func (m *defaultInterviewDialoguesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interviewDialoguesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInterviewDialoguesModel) tableName() string {
	return m.table
}
