// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	jobProfilesFieldNames          = builder.RawFieldNames(&JobProfiles{})
	jobProfilesRows                = strings.Join(jobProfilesFieldNames, ",")
	jobProfilesRowsExpectAutoSet   = strings.Join(stringx.Remove(jobProfilesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	jobProfilesRowsWithPlaceHolder = strings.Join(stringx.Remove(jobProfilesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheJobProfilesIdPrefix = "cache:jobProfiles:id:"
)

type (
	jobProfilesModel interface {
		Insert(ctx context.Context, data *JobProfiles) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*JobProfiles, error)
		Update(ctx context.Context, data *JobProfiles) error
		Delete(ctx context.Context, id string) error
	}

	defaultJobProfilesModel struct {
		sqlc.CachedConn
		table string
	}

	JobProfiles struct {
		Id          string         `db:"id"`          // 唯一标识 (UUID)
		CreatorId   string         `db:"creator_id"`  // 创建人ID
		Name        string         `db:"name"`        // 岗位名称
		Description sql.NullString `db:"description"` // 岗位描述
		CreatedAt   time.Time      `db:"created_at"`  // 创建时间
	}
)

func newJobProfilesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultJobProfilesModel {
	return &defaultJobProfilesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`job_profiles`",
	}
}

func (m *defaultJobProfilesModel) Delete(ctx context.Context, id string) error {
	jobProfilesIdKey := fmt.Sprintf("%s%v", cacheJobProfilesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, jobProfilesIdKey)
	return err
}

func (m *defaultJobProfilesModel) FindOne(ctx context.Context, id string) (*JobProfiles, error) {
	jobProfilesIdKey := fmt.Sprintf("%s%v", cacheJobProfilesIdPrefix, id)
	var resp JobProfiles
	err := m.QueryRowCtx(ctx, &resp, jobProfilesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", jobProfilesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJobProfilesModel) Insert(ctx context.Context, data *JobProfiles) (sql.Result, error) {
	jobProfilesIdKey := fmt.Sprintf("%s%v", cacheJobProfilesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, jobProfilesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.CreatorId, data.Name, data.Description)
	}, jobProfilesIdKey)
	return ret, err
}

func (m *defaultJobProfilesModel) Update(ctx context.Context, data *JobProfiles) error {
	jobProfilesIdKey := fmt.Sprintf("%s%v", cacheJobProfilesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, jobProfilesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CreatorId, data.Name, data.Description, data.Id)
	}, jobProfilesIdKey)
	return err
}

func (m *defaultJobProfilesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheJobProfilesIdPrefix, primary)
}

func (m *defaultJobProfilesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", jobProfilesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultJobProfilesModel) tableName() string {
	return m.table
}
