// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	practiceSessionsFieldNames          = builder.RawFieldNames(&PracticeSessions{})
	practiceSessionsRows                = strings.Join(practiceSessionsFieldNames, ",")
	practiceSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(practiceSessionsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	practiceSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(practiceSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePracticeSessionsIdPrefix = "cache:practiceSessions:id:"
)

type (
	practiceSessionsModel interface {
		Insert(ctx context.Context, data *PracticeSessions) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*PracticeSessions, error)
		Update(ctx context.Context, data *PracticeSessions) error
		Delete(ctx context.Context, id string) error
	}

	defaultPracticeSessionsModel struct {
		sqlc.CachedConn
		table string
	}

	PracticeSessions struct {
		Id               string         `db:"id"`                // 唯一标识 (UUID)
		UserId           string         `db:"user_id"`           // 用户ID
		UserProfileId    string         `db:"user_profile_id"`   // 用户档案ID
		ScenarioId       string         `db:"scenario_id"`       // 场景ID
		Status           string         `db:"status"`            // 状态
		EvaluationReport sql.NullString `db:"evaluation_report"` // 口语练习最终评估报告
		CreatedAt        time.Time      `db:"created_at"`        // 创建时间
		UpdatedAt        time.Time      `db:"updated_at"`        // 更新时间
	}
)

func newPracticeSessionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPracticeSessionsModel {
	return &defaultPracticeSessionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`practice_sessions`",
	}
}

func (m *defaultPracticeSessionsModel) Delete(ctx context.Context, id string) error {
	practiceSessionsIdKey := fmt.Sprintf("%s%v", cachePracticeSessionsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, practiceSessionsIdKey)
	return err
}

func (m *defaultPracticeSessionsModel) FindOne(ctx context.Context, id string) (*PracticeSessions, error) {
	practiceSessionsIdKey := fmt.Sprintf("%s%v", cachePracticeSessionsIdPrefix, id)
	var resp PracticeSessions
	err := m.QueryRowCtx(ctx, &resp, practiceSessionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", practiceSessionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPracticeSessionsModel) Insert(ctx context.Context, data *PracticeSessions) (sql.Result, error) {
	practiceSessionsIdKey := fmt.Sprintf("%s%v", cachePracticeSessionsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, practiceSessionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.UserProfileId, data.ScenarioId, data.Status, data.EvaluationReport)
	}, practiceSessionsIdKey)
	return ret, err
}

func (m *defaultPracticeSessionsModel) Update(ctx context.Context, data *PracticeSessions) error {
	practiceSessionsIdKey := fmt.Sprintf("%s%v", cachePracticeSessionsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, practiceSessionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.UserProfileId, data.ScenarioId, data.Status, data.EvaluationReport, data.Id)
	}, practiceSessionsIdKey)
	return err
}

func (m *defaultPracticeSessionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePracticeSessionsIdPrefix, primary)
}

func (m *defaultPracticeSessionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", practiceSessionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPracticeSessionsModel) tableName() string {
	return m.table
}
