// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	resumesFieldNames          = builder.RawFieldNames(&Resumes{})
	resumesRows                = strings.Join(resumesFieldNames, ",")
	resumesRowsExpectAutoSet   = strings.Join(stringx.Remove(resumesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	resumesRowsWithPlaceHolder = strings.Join(stringx.Remove(resumesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheResumesIdPrefix = "cache:resumes:id:"
)

type (
	resumesModel interface {
		Insert(ctx context.Context, data *Resumes) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Resumes, error)
		Update(ctx context.Context, data *Resumes) error
		Delete(ctx context.Context, id string) error
	}

	defaultResumesModel struct {
		sqlc.CachedConn
		table string
	}

	Resumes struct {
		Id        string         `db:"id"`         // 唯一标识 (UUID)
		UserId    string         `db:"user_id"`    // 用户ID
		Content   string         `db:"content"`    // 简历内容(Markdown或纯文本格式)
		PdfUrl    sql.NullString `db:"pdf_url"`    // pdf地址
		CreatedAt time.Time      `db:"created_at"` // 创建时间
	}
)

func newResumesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultResumesModel {
	return &defaultResumesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`resumes`",
	}
}

func (m *defaultResumesModel) Delete(ctx context.Context, id string) error {
	resumesIdKey := fmt.Sprintf("%s%v", cacheResumesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, resumesIdKey)
	return err
}

func (m *defaultResumesModel) FindOne(ctx context.Context, id string) (*Resumes, error) {
	resumesIdKey := fmt.Sprintf("%s%v", cacheResumesIdPrefix, id)
	var resp Resumes
	err := m.QueryRowCtx(ctx, &resp, resumesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", resumesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResumesModel) Insert(ctx context.Context, data *Resumes) (sql.Result, error) {
	resumesIdKey := fmt.Sprintf("%s%v", cacheResumesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, resumesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Content, data.PdfUrl)
	}, resumesIdKey)
	return ret, err
}

func (m *defaultResumesModel) Update(ctx context.Context, data *Resumes) error {
	resumesIdKey := fmt.Sprintf("%s%v", cacheResumesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, resumesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Content, data.PdfUrl, data.Id)
	}, resumesIdKey)
	return err
}

func (m *defaultResumesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheResumesIdPrefix, primary)
}

func (m *defaultResumesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", resumesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultResumesModel) tableName() string {
	return m.table
}
