// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scenariosFieldNames          = builder.RawFieldNames(&Scenarios{})
	scenariosRows                = strings.Join(scenariosFieldNames, ",")
	scenariosRowsExpectAutoSet   = strings.Join(stringx.Remove(scenariosFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scenariosRowsWithPlaceHolder = strings.Join(stringx.Remove(scenariosFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheScenariosIdPrefix = "cache:scenarios:id:"
)

type (
	scenariosModel interface {
		Insert(ctx context.Context, data *Scenarios) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Scenarios, error)
		Update(ctx context.Context, data *Scenarios) error
		Delete(ctx context.Context, id string) error
	}

	defaultScenariosModel struct {
		sqlc.CachedConn
		table string
	}

	Scenarios struct {
		Id          string         `db:"id"`          // 唯一标识 (UUID)
		CreatorId   string         `db:"creator_id"`  // 创建人ID
		Name        string         `db:"name"`        // 场景名称 (例如：Ordering Food)
		Description sql.NullString `db:"description"` // 场景上下文描述/系统引导 Prompt
		CreatedAt   time.Time      `db:"created_at"`  // 创建时间
	}
)

func newScenariosModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultScenariosModel {
	return &defaultScenariosModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`scenarios`",
	}
}

func (m *defaultScenariosModel) Delete(ctx context.Context, id string) error {
	scenariosIdKey := fmt.Sprintf("%s%v", cacheScenariosIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, scenariosIdKey)
	return err
}

func (m *defaultScenariosModel) FindOne(ctx context.Context, id string) (*Scenarios, error) {
	scenariosIdKey := fmt.Sprintf("%s%v", cacheScenariosIdPrefix, id)
	var resp Scenarios
	err := m.QueryRowCtx(ctx, &resp, scenariosIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scenariosRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScenariosModel) Insert(ctx context.Context, data *Scenarios) (sql.Result, error) {
	scenariosIdKey := fmt.Sprintf("%s%v", cacheScenariosIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, scenariosRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.CreatorId, data.Name, data.Description)
	}, scenariosIdKey)
	return ret, err
}

func (m *defaultScenariosModel) Update(ctx context.Context, data *Scenarios) error {
	scenariosIdKey := fmt.Sprintf("%s%v", cacheScenariosIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, scenariosRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CreatorId, data.Name, data.Description, data.Id)
	}, scenariosIdKey)
	return err
}

func (m *defaultScenariosModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheScenariosIdPrefix, primary)
}

func (m *defaultScenariosModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scenariosRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultScenariosModel) tableName() string {
	return m.table
}
