// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userProfilesFieldNames          = builder.RawFieldNames(&UserProfiles{})
	userProfilesRows                = strings.Join(userProfilesFieldNames, ",")
	userProfilesRowsExpectAutoSet   = strings.Join(stringx.Remove(userProfilesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userProfilesRowsWithPlaceHolder = strings.Join(stringx.Remove(userProfilesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserProfilesIdPrefix = "cache:userProfiles:id:"
)

type (
	userProfilesModel interface {
		Insert(ctx context.Context, data *UserProfiles) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*UserProfiles, error)
		Update(ctx context.Context, data *UserProfiles) error
		Delete(ctx context.Context, id string) error
	}

	defaultUserProfilesModel struct {
		sqlc.CachedConn
		table string
	}

	UserProfiles struct {
		Id             string    `db:"id"`              // 唯一标识 (UUID)
		UserId         string    `db:"user_id"`         // 用户ID
		EnglishLevel   string    `db:"english_level"`   // 英语水平级别 (beginner/intermediate/advanced)
		LearningTarget string    `db:"learning_target"` // 学习目标 (例如：雅思口语、西餐点餐、日常会话等)
		CreatedAt      time.Time `db:"created_at"`      // 创建时间
	}
)

func newUserProfilesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserProfilesModel {
	return &defaultUserProfilesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_profiles`",
	}
}

func (m *defaultUserProfilesModel) Delete(ctx context.Context, id string) error {
	userProfilesIdKey := fmt.Sprintf("%s%v", cacheUserProfilesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userProfilesIdKey)
	return err
}

func (m *defaultUserProfilesModel) FindOne(ctx context.Context, id string) (*UserProfiles, error) {
	userProfilesIdKey := fmt.Sprintf("%s%v", cacheUserProfilesIdPrefix, id)
	var resp UserProfiles
	err := m.QueryRowCtx(ctx, &resp, userProfilesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userProfilesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfilesModel) Insert(ctx context.Context, data *UserProfiles) (sql.Result, error) {
	userProfilesIdKey := fmt.Sprintf("%s%v", cacheUserProfilesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userProfilesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.EnglishLevel, data.LearningTarget)
	}, userProfilesIdKey)
	return ret, err
}

func (m *defaultUserProfilesModel) Update(ctx context.Context, data *UserProfiles) error {
	userProfilesIdKey := fmt.Sprintf("%s%v", cacheUserProfilesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userProfilesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.EnglishLevel, data.LearningTarget, data.Id)
	}, userProfilesIdKey)
	return err
}

func (m *defaultUserProfilesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserProfilesIdPrefix, primary)
}

func (m *defaultUserProfilesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userProfilesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserProfilesModel) tableName() string {
	return m.table
}
