// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"ai_interview/interview_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 提交并设置用户背景档案
				Method:  http.MethodPost,
				Path:    "/",
				Handler: CreateUserProfileHandler(serverCtx),
			},
			{
				// 获取用户档案信息
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: GetUserProfileHandler(serverCtx),
			},
			{
				// 获取上传学习背景文件的预签名URL (备用)
				Method:  http.MethodPost,
				Path:    "/upload-url",
				Handler: GenerateUploadUrlHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user-profiles"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建练习场景
				Method:  http.MethodPost,
				Path:    "/",
				Handler: CreateScenarioHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/scenarios"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建口语练习会话
				Method:  http.MethodPost,
				Path:    "/",
				Handler: CreateSessionHandler(serverCtx),
			},
			{
				// 获取口语练习历史列表
				Method:  http.MethodGet,
				Path:    "/",
				Handler: ListSessionsHandler(serverCtx),
			},
			{
				// 获取口语练习详情
				Method:  http.MethodGet,
				Path:    "/:session_id",
				Handler: GetSessionDetailHandler(serverCtx),
			},
			{
				// 删除口语练习记录
				Method:  http.MethodDelete,
				Path:    "/:session_id",
				Handler: DeleteSessionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/practices"),
	)
}
