// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"ai_interview/interview_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 提交通知，触发简历解析入库
				Method:  http.MethodPost,
				Path:    "/",
				Handler: CreateResumeHandler(serverCtx),
			},
			{
				// 获取简历详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: GetResumeHandler(serverCtx),
			},
			{
				// 获取上传简历的预签名URL
				Method:  http.MethodPost,
				Path:    "/upload-url",
				Handler: GenerateUploadUrlHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/resumes"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建面试岗位
				Method:  http.MethodPost,
				Path:    "/",
				Handler: CreateJobProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/job-profiles"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建面试会话
				Method:  http.MethodPost,
				Path:    "/",
				Handler: CreateSessionHandler(serverCtx),
			},
			{
				// 获取面试历史列表
				Method:  http.MethodGet,
				Path:    "/",
				Handler: ListSessionsHandler(serverCtx),
			},
			{
				// 获取面试详情
				Method:  http.MethodGet,
				Path:    "/:session_id",
				Handler: GetSessionDetailHandler(serverCtx),
			},
			{
				// 删除面试记录
				Method:  http.MethodDelete,
				Path:    "/:session_id",
				Handler: DeleteSessionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/interviews"),
	)
}
