// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateJobProfileReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateJobProfileResp struct {
	Id string `json:"id"`
}

type CreateResumeReq struct {
	ObjectKey string `json:"object_key"`
}

type CreateResumeResp struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type CreateSessionReq struct {
	ResumeId     string `json:"resume_id"`
	JobProfileId string `json:"job_profile_id"`
}

type CreateSessionResp struct {
	SessionId string `json:"session_id"`
}

type DeleteSessionReq struct {
	SessionId string `path:"session_id"`
}

type DeleteSessionResp struct {
	Success bool `json:"success"`
}

type GenerateUploadUrlReq struct {
	Filename string `json:"filename"`
}

type GenerateUploadUrlResp struct {
	UploadUrl string `json:"upload_url"`
	ObjectKey string `json:"object_key"`
}

type GetResumeReq struct {
	Id string `path:"id"`
}

type GetResumeResp struct {
	Id          string `json:"id"`
	RawText     string `json:"raw_text"`
	Status      string `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	DownloadUrl string `json:"download_url"`
}

type GetSessionDetailReq struct {
	SessionId string `path:"session_id"`
}

type GetSessionDetailResp struct {
	SessionId    string `json:"session_id"`
	JobTitle     string `json:"job_title"`
	Transcript   string `json:"transcript"`
	OverallScore int32  `json:"overall_score"`
	Commentary   string `json:"commentary"`
}

type GetUserInfoResp struct {
	Id              string `json:"id"`
	Username        string `json:"username"`
	Email           string `json:"email"`
	DailyFreeTokens uint32 `json:"daily_free_tokens"`
	RechargeTokens  uint64 `json:"recharge_tokens"`
}

type InterviewSession struct {
	SessionId    string `json:"session_id"`
	JobTitle     string `json:"job_title"`
	Status       string `json:"status"`
	CreatedAt    int64  `json:"created_at"`
	OverallScore int32  `json:"overall_score"`
}

type ListSessionsResp struct {
	Sessions []InterviewSession `json:"sessions"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id string `json:"id"`
}
