// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: core.proto

package server

import (
	"context"

	"ai_interview/rpc/core/core"
	"ai_interview/rpc/core/internal/logic"
	"ai_interview/rpc/core/internal/svc"
)

type CoreServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedCoreServer
}

func NewCoreServer(svcCtx *svc.ServiceContext) *CoreServer {
	return &CoreServer{
		svcCtx: svcCtx,
	}
}

// Resume & OSS
func (s *CoreServer) GenerateUploadUrl(ctx context.Context, in *core.GenerateUploadUrlReq) (*core.GenerateUploadUrlResp, error) {
	l := logic.NewGenerateUploadUrlLogic(ctx, s.svcCtx)
	return l.GenerateUploadUrl(in)
}

func (s *CoreServer) CreateResume(ctx context.Context, in *core.CreateResumeReq) (*core.CreateResumeResp, error) {
	l := logic.NewCreateResumeLogic(ctx, s.svcCtx)
	return l.CreateResume(in)
}

func (s *CoreServer) GetResume(ctx context.Context, in *core.GetResumeReq) (*core.GetResumeResp, error) {
	l := logic.NewGetResumeLogic(ctx, s.svcCtx)
	return l.GetResume(in)
}

// Job Profiles
func (s *CoreServer) CreateJobProfile(ctx context.Context, in *core.CreateJobProfileReq) (*core.CreateJobProfileResp, error) {
	l := logic.NewCreateJobProfileLogic(ctx, s.svcCtx)
	return l.CreateJobProfile(in)
}

func (s *CoreServer) GetJobProfile(ctx context.Context, in *core.GetJobProfileReq) (*core.GetJobProfileResp, error) {
	l := logic.NewGetJobProfileLogic(ctx, s.svcCtx)
	return l.GetJobProfile(in)
}

// Interview Sessions
func (s *CoreServer) CreateSession(ctx context.Context, in *core.CreateSessionReq) (*core.CreateSessionResp, error) {
	l := logic.NewCreateSessionLogic(ctx, s.svcCtx)
	return l.CreateSession(in)
}

func (s *CoreServer) UpdateSessionStatus(ctx context.Context, in *core.UpdateSessionStatusReq) (*core.UpdateSessionStatusResp, error) {
	l := logic.NewUpdateSessionStatusLogic(ctx, s.svcCtx)
	return l.UpdateSessionStatus(in)
}

// Interview Dialogues
func (s *CoreServer) AddDialogue(ctx context.Context, in *core.AddDialogueReq) (*core.AddDialogueResp, error) {
	l := logic.NewAddDialogueLogic(ctx, s.svcCtx)
	return l.AddDialogue(in)
}

func (s *CoreServer) UpdateDialogueEvaluation(ctx context.Context, in *core.UpdateDialogueEvaluationReq) (*core.UpdateDialogueEvaluationResp, error) {
	l := logic.NewUpdateDialogueEvaluationLogic(ctx, s.svcCtx)
	return l.UpdateDialogueEvaluation(in)
}

// 面试上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
func (s *CoreServer) GetInterviewContext(ctx context.Context, in *core.GetInterviewContextReq) (*core.GetInterviewContextResp, error) {
	l := logic.NewGetInterviewContextLogic(ctx, s.svcCtx)
	return l.GetInterviewContext(in)
}

// 面试列表与详情
func (s *CoreServer) ListSessions(ctx context.Context, in *core.ListSessionsReq) (*core.ListSessionsResp, error) {
	l := logic.NewListSessionsLogic(ctx, s.svcCtx)
	return l.ListSessions(in)
}

func (s *CoreServer) GetSessionDetail(ctx context.Context, in *core.GetSessionDetailReq) (*core.GetSessionDetailResp, error) {
	l := logic.NewGetSessionDetailLogic(ctx, s.svcCtx)
	return l.GetSessionDetail(in)
}

func (s *CoreServer) DeleteSession(ctx context.Context, in *core.DeleteSessionReq) (*core.DeleteSessionResp, error) {
	l := logic.NewDeleteSessionLogic(ctx, s.svcCtx)
	return l.DeleteSession(in)
}
