// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: core.proto

package server

import (
	"context"

	"ai_companion/rpc/core/core"
	"ai_companion/rpc/core/internal/logic"
	"ai_companion/rpc/core/internal/svc"
)

type CoreServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedCoreServer
}

func NewCoreServer(svcCtx *svc.ServiceContext) *CoreServer {
	return &CoreServer{
		svcCtx: svcCtx,
	}
}

// User Profile & OSS
func (s *CoreServer) GenerateUploadUrl(ctx context.Context, in *core.GenerateUploadUrlReq) (*core.GenerateUploadUrlResp, error) {
	l := logic.NewGenerateUploadUrlLogic(ctx, s.svcCtx)
	return l.GenerateUploadUrl(in)
}

func (s *CoreServer) CreateUserProfile(ctx context.Context, in *core.CreateUserProfileReq) (*core.CreateUserProfileResp, error) {
	l := logic.NewCreateUserProfileLogic(ctx, s.svcCtx)
	return l.CreateUserProfile(in)
}

func (s *CoreServer) GetUserProfile(ctx context.Context, in *core.GetUserProfileReq) (*core.GetUserProfileResp, error) {
	l := logic.NewGetUserProfileLogic(ctx, s.svcCtx)
	return l.GetUserProfile(in)
}

// Scenarios
func (s *CoreServer) CreateScenario(ctx context.Context, in *core.CreateScenarioReq) (*core.CreateScenarioResp, error) {
	l := logic.NewCreateScenarioLogic(ctx, s.svcCtx)
	return l.CreateScenario(in)
}

func (s *CoreServer) GetScenario(ctx context.Context, in *core.GetScenarioReq) (*core.GetScenarioResp, error) {
	l := logic.NewGetScenarioLogic(ctx, s.svcCtx)
	return l.GetScenario(in)
}

// Practice Sessions
func (s *CoreServer) CreateSession(ctx context.Context, in *core.CreateSessionReq) (*core.CreateSessionResp, error) {
	l := logic.NewCreateSessionLogic(ctx, s.svcCtx)
	return l.CreateSession(in)
}

func (s *CoreServer) UpdateSessionStatus(ctx context.Context, in *core.UpdateSessionStatusReq) (*core.UpdateSessionStatusResp, error) {
	l := logic.NewUpdateSessionStatusLogic(ctx, s.svcCtx)
	return l.UpdateSessionStatus(in)
}

// Dialogues
func (s *CoreServer) AddDialogue(ctx context.Context, in *core.AddDialogueReq) (*core.AddDialogueResp, error) {
	l := logic.NewAddDialogueLogic(ctx, s.svcCtx)
	return l.AddDialogue(in)
}

func (s *CoreServer) UpdateDialogueEvaluation(ctx context.Context, in *core.UpdateDialogueEvaluationReq) (*core.UpdateDialogueEvaluationResp, error) {
	l := logic.NewUpdateDialogueEvaluationLogic(ctx, s.svcCtx)
	return l.UpdateDialogueEvaluation(in)
}

// 上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
func (s *CoreServer) GetPracticeContext(ctx context.Context, in *core.GetPracticeContextReq) (*core.GetPracticeContextResp, error) {
	l := logic.NewGetPracticeContextLogic(ctx, s.svcCtx)
	return l.GetPracticeContext(in)
}

// 列表与详情
func (s *CoreServer) ListSessions(ctx context.Context, in *core.ListSessionsReq) (*core.ListSessionsResp, error) {
	l := logic.NewListSessionsLogic(ctx, s.svcCtx)
	return l.ListSessions(in)
}

func (s *CoreServer) GetSessionDetail(ctx context.Context, in *core.GetSessionDetailReq) (*core.GetSessionDetailResp, error) {
	l := logic.NewGetSessionDetailLogic(ctx, s.svcCtx)
	return l.GetSessionDetail(in)
}

func (s *CoreServer) DeleteSession(ctx context.Context, in *core.DeleteSessionReq) (*core.DeleteSessionResp, error) {
	l := logic.NewDeleteSessionLogic(ctx, s.svcCtx)
	return l.DeleteSession(in)
}
