// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Core_GenerateUploadUrl_FullMethodName        = "/core.Core/GenerateUploadUrl"
	Core_CreateResume_FullMethodName             = "/core.Core/CreateResume"
	Core_GetResume_FullMethodName                = "/core.Core/GetResume"
	Core_CreateJobProfile_FullMethodName         = "/core.Core/CreateJobProfile"
	Core_GetJobProfile_FullMethodName            = "/core.Core/GetJobProfile"
	Core_CreateSession_FullMethodName            = "/core.Core/CreateSession"
	Core_UpdateSessionStatus_FullMethodName      = "/core.Core/UpdateSessionStatus"
	Core_AddDialogue_FullMethodName              = "/core.Core/AddDialogue"
	Core_UpdateDialogueEvaluation_FullMethodName = "/core.Core/UpdateDialogueEvaluation"
	Core_GetInterviewContext_FullMethodName      = "/core.Core/GetInterviewContext"
	Core_ListSessions_FullMethodName             = "/core.Core/ListSessions"
	Core_GetSessionDetail_FullMethodName         = "/core.Core/GetSessionDetail"
	Core_DeleteSession_FullMethodName            = "/core.Core/DeleteSession"
)

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreClient interface {
	// Resume & OSS
	GenerateUploadUrl(ctx context.Context, in *GenerateUploadUrlReq, opts ...grpc.CallOption) (*GenerateUploadUrlResp, error)
	CreateResume(ctx context.Context, in *CreateResumeReq, opts ...grpc.CallOption) (*CreateResumeResp, error)
	GetResume(ctx context.Context, in *GetResumeReq, opts ...grpc.CallOption) (*GetResumeResp, error)
	// Job Profiles
	CreateJobProfile(ctx context.Context, in *CreateJobProfileReq, opts ...grpc.CallOption) (*CreateJobProfileResp, error)
	GetJobProfile(ctx context.Context, in *GetJobProfileReq, opts ...grpc.CallOption) (*GetJobProfileResp, error)
	// Interview Sessions
	CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error)
	UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error)
	// Interview Dialogues
	AddDialogue(ctx context.Context, in *AddDialogueReq, opts ...grpc.CallOption) (*AddDialogueResp, error)
	UpdateDialogueEvaluation(ctx context.Context, in *UpdateDialogueEvaluationReq, opts ...grpc.CallOption) (*UpdateDialogueEvaluationResp, error)
	// 面试上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
	GetInterviewContext(ctx context.Context, in *GetInterviewContextReq, opts ...grpc.CallOption) (*GetInterviewContextResp, error)
	// 面试列表与详情
	ListSessions(ctx context.Context, in *ListSessionsReq, opts ...grpc.CallOption) (*ListSessionsResp, error)
	GetSessionDetail(ctx context.Context, in *GetSessionDetailReq, opts ...grpc.CallOption) (*GetSessionDetailResp, error)
	DeleteSession(ctx context.Context, in *DeleteSessionReq, opts ...grpc.CallOption) (*DeleteSessionResp, error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) GenerateUploadUrl(ctx context.Context, in *GenerateUploadUrlReq, opts ...grpc.CallOption) (*GenerateUploadUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateUploadUrlResp)
	err := c.cc.Invoke(ctx, Core_GenerateUploadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateResume(ctx context.Context, in *CreateResumeReq, opts ...grpc.CallOption) (*CreateResumeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResumeResp)
	err := c.cc.Invoke(ctx, Core_CreateResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetResume(ctx context.Context, in *GetResumeReq, opts ...grpc.CallOption) (*GetResumeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResumeResp)
	err := c.cc.Invoke(ctx, Core_GetResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateJobProfile(ctx context.Context, in *CreateJobProfileReq, opts ...grpc.CallOption) (*CreateJobProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobProfileResp)
	err := c.cc.Invoke(ctx, Core_CreateJobProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetJobProfile(ctx context.Context, in *GetJobProfileReq, opts ...grpc.CallOption) (*GetJobProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobProfileResp)
	err := c.cc.Invoke(ctx, Core_GetJobProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResp)
	err := c.cc.Invoke(ctx, Core_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionStatusResp)
	err := c.cc.Invoke(ctx, Core_UpdateSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) AddDialogue(ctx context.Context, in *AddDialogueReq, opts ...grpc.CallOption) (*AddDialogueResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDialogueResp)
	err := c.cc.Invoke(ctx, Core_AddDialogue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpdateDialogueEvaluation(ctx context.Context, in *UpdateDialogueEvaluationReq, opts ...grpc.CallOption) (*UpdateDialogueEvaluationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDialogueEvaluationResp)
	err := c.cc.Invoke(ctx, Core_UpdateDialogueEvaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetInterviewContext(ctx context.Context, in *GetInterviewContextReq, opts ...grpc.CallOption) (*GetInterviewContextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterviewContextResp)
	err := c.cc.Invoke(ctx, Core_GetInterviewContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ListSessions(ctx context.Context, in *ListSessionsReq, opts ...grpc.CallOption) (*ListSessionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResp)
	err := c.cc.Invoke(ctx, Core_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetSessionDetail(ctx context.Context, in *GetSessionDetailReq, opts ...grpc.CallOption) (*GetSessionDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionDetailResp)
	err := c.cc.Invoke(ctx, Core_GetSessionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) DeleteSession(ctx context.Context, in *DeleteSessionReq, opts ...grpc.CallOption) (*DeleteSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResp)
	err := c.cc.Invoke(ctx, Core_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServer is the server API for Core service.
// All implementations must embed UnimplementedCoreServer
// for forward compatibility.
type CoreServer interface {
	// Resume & OSS
	GenerateUploadUrl(context.Context, *GenerateUploadUrlReq) (*GenerateUploadUrlResp, error)
	CreateResume(context.Context, *CreateResumeReq) (*CreateResumeResp, error)
	GetResume(context.Context, *GetResumeReq) (*GetResumeResp, error)
	// Job Profiles
	CreateJobProfile(context.Context, *CreateJobProfileReq) (*CreateJobProfileResp, error)
	GetJobProfile(context.Context, *GetJobProfileReq) (*GetJobProfileResp, error)
	// Interview Sessions
	CreateSession(context.Context, *CreateSessionReq) (*CreateSessionResp, error)
	UpdateSessionStatus(context.Context, *UpdateSessionStatusReq) (*UpdateSessionStatusResp, error)
	// Interview Dialogues
	AddDialogue(context.Context, *AddDialogueReq) (*AddDialogueResp, error)
	UpdateDialogueEvaluation(context.Context, *UpdateDialogueEvaluationReq) (*UpdateDialogueEvaluationResp, error)
	// 面试上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
	GetInterviewContext(context.Context, *GetInterviewContextReq) (*GetInterviewContextResp, error)
	// 面试列表与详情
	ListSessions(context.Context, *ListSessionsReq) (*ListSessionsResp, error)
	GetSessionDetail(context.Context, *GetSessionDetailReq) (*GetSessionDetailResp, error)
	DeleteSession(context.Context, *DeleteSessionReq) (*DeleteSessionResp, error)
	mustEmbedUnimplementedCoreServer()
}

// UnimplementedCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServer struct{}

func (UnimplementedCoreServer) GenerateUploadUrl(context.Context, *GenerateUploadUrlReq) (*GenerateUploadUrlResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateUploadUrl not implemented")
}
func (UnimplementedCoreServer) CreateResume(context.Context, *CreateResumeReq) (*CreateResumeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateResume not implemented")
}
func (UnimplementedCoreServer) GetResume(context.Context, *GetResumeReq) (*GetResumeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResume not implemented")
}
func (UnimplementedCoreServer) CreateJobProfile(context.Context, *CreateJobProfileReq) (*CreateJobProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJobProfile not implemented")
}
func (UnimplementedCoreServer) GetJobProfile(context.Context, *GetJobProfileReq) (*GetJobProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobProfile not implemented")
}
func (UnimplementedCoreServer) CreateSession(context.Context, *CreateSessionReq) (*CreateSessionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedCoreServer) UpdateSessionStatus(context.Context, *UpdateSessionStatusReq) (*UpdateSessionStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSessionStatus not implemented")
}
func (UnimplementedCoreServer) AddDialogue(context.Context, *AddDialogueReq) (*AddDialogueResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDialogue not implemented")
}
func (UnimplementedCoreServer) UpdateDialogueEvaluation(context.Context, *UpdateDialogueEvaluationReq) (*UpdateDialogueEvaluationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDialogueEvaluation not implemented")
}
func (UnimplementedCoreServer) GetInterviewContext(context.Context, *GetInterviewContextReq) (*GetInterviewContextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterviewContext not implemented")
}
func (UnimplementedCoreServer) ListSessions(context.Context, *ListSessionsReq) (*ListSessionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedCoreServer) GetSessionDetail(context.Context, *GetSessionDetailReq) (*GetSessionDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionDetail not implemented")
}
func (UnimplementedCoreServer) DeleteSession(context.Context, *DeleteSessionReq) (*DeleteSessionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedCoreServer) mustEmbedUnimplementedCoreServer() {}
func (UnimplementedCoreServer) testEmbeddedByValue()              {}

// UnsafeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServer will
// result in compilation errors.
type UnsafeCoreServer interface {
	mustEmbedUnimplementedCoreServer()
}

func RegisterCoreServer(s grpc.ServiceRegistrar, srv CoreServer) {
	// If the following call panics, it indicates UnimplementedCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Core_ServiceDesc, srv)
}

func _Core_GenerateUploadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUploadUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GenerateUploadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GenerateUploadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GenerateUploadUrl(ctx, req.(*GenerateUploadUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateResume(ctx, req.(*CreateResumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetResume(ctx, req.(*GetResumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateJobProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateJobProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateJobProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateJobProfile(ctx, req.(*CreateJobProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetJobProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetJobProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetJobProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetJobProfile(ctx, req.(*GetJobProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateSession(ctx, req.(*CreateSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpdateSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpdateSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_UpdateSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpdateSessionStatus(ctx, req.(*UpdateSessionStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_AddDialogue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDialogueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).AddDialogue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_AddDialogue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).AddDialogue(ctx, req.(*AddDialogueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpdateDialogueEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDialogueEvaluationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpdateDialogueEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_UpdateDialogueEvaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpdateDialogueEvaluation(ctx, req.(*UpdateDialogueEvaluationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetInterviewContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterviewContextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetInterviewContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetInterviewContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetInterviewContext(ctx, req.(*GetInterviewContextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ListSessions(ctx, req.(*ListSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetSessionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetSessionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetSessionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetSessionDetail(ctx, req.(*GetSessionDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).DeleteSession(ctx, req.(*DeleteSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Core_ServiceDesc is the grpc.ServiceDesc for Core service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Core_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateUploadUrl",
			Handler:    _Core_GenerateUploadUrl_Handler,
		},
		{
			MethodName: "CreateResume",
			Handler:    _Core_CreateResume_Handler,
		},
		{
			MethodName: "GetResume",
			Handler:    _Core_GetResume_Handler,
		},
		{
			MethodName: "CreateJobProfile",
			Handler:    _Core_CreateJobProfile_Handler,
		},
		{
			MethodName: "GetJobProfile",
			Handler:    _Core_GetJobProfile_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Core_CreateSession_Handler,
		},
		{
			MethodName: "UpdateSessionStatus",
			Handler:    _Core_UpdateSessionStatus_Handler,
		},
		{
			MethodName: "AddDialogue",
			Handler:    _Core_AddDialogue_Handler,
		},
		{
			MethodName: "UpdateDialogueEvaluation",
			Handler:    _Core_UpdateDialogueEvaluation_Handler,
		},
		{
			MethodName: "GetInterviewContext",
			Handler:    _Core_GetInterviewContext_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Core_ListSessions_Handler,
		},
		{
			MethodName: "GetSessionDetail",
			Handler:    _Core_GetSessionDetail_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _Core_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
