// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateUploadUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadUrlReq) Reset() {
	*x = GenerateUploadUrlReq{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadUrlReq) ProtoMessage() {}

func (x *GenerateUploadUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadUrlReq.ProtoReflect.Descriptor instead.
func (*GenerateUploadUrlReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateUploadUrlReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type GenerateUploadUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // 预签名 PUT URL
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // 后续落库用的 OSS Key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadUrlResp) Reset() {
	*x = GenerateUploadUrlResp{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadUrlResp) ProtoMessage() {}

func (x *GenerateUploadUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadUrlResp.ProtoReflect.Descriptor instead.
func (*GenerateUploadUrlResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateUploadUrlResp) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GenerateUploadUrlResp) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type CreateUserProfileReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EnglishLevel   string                 `protobuf:"bytes,2,opt,name=english_level,json=englishLevel,proto3" json:"english_level,omitempty"`       // beginner/intermediate/advanced
	LearningTarget string                 `protobuf:"bytes,3,opt,name=learning_target,json=learningTarget,proto3" json:"learning_target,omitempty"` // 学习目标
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserProfileReq) Reset() {
	*x = CreateUserProfileReq{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileReq) ProtoMessage() {}

func (x *CreateUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileReq.ProtoReflect.Descriptor instead.
func (*CreateUserProfileReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserProfileReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserProfileReq) GetEnglishLevel() string {
	if x != nil {
		return x.EnglishLevel
	}
	return ""
}

func (x *CreateUserProfileReq) GetLearningTarget() string {
	if x != nil {
		return x.LearningTarget
	}
	return ""
}

type CreateUserProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 解析状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileResp) Reset() {
	*x = CreateUserProfileResp{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileResp) ProtoMessage() {}

func (x *CreateUserProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileResp.ProtoReflect.Descriptor instead.
func (*CreateUserProfileResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserProfileResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserProfileResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileReq) Reset() {
	*x = GetUserProfileReq{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileReq) ProtoMessage() {}

func (x *GetUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileReq.ProtoReflect.Descriptor instead.
func (*GetUserProfileReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProfileReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserProfileResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EnglishLevel   string                 `protobuf:"bytes,3,opt,name=english_level,json=englishLevel,proto3" json:"english_level,omitempty"`
	LearningTarget string                 `protobuf:"bytes,4,opt,name=learning_target,json=learningTarget,proto3" json:"learning_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserProfileResp) Reset() {
	*x = GetUserProfileResp{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResp) ProtoMessage() {}

func (x *GetUserProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResp.ProtoReflect.Descriptor instead.
func (*GetUserProfileResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserProfileResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserProfileResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProfileResp) GetEnglishLevel() string {
	if x != nil {
		return x.EnglishLevel
	}
	return ""
}

func (x *GetUserProfileResp) GetLearningTarget() string {
	if x != nil {
		return x.LearningTarget
	}
	return ""
}

type CreateScenarioReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScenarioReq) Reset() {
	*x = CreateScenarioReq{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScenarioReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScenarioReq) ProtoMessage() {}

func (x *CreateScenarioReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScenarioReq.ProtoReflect.Descriptor instead.
func (*CreateScenarioReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *CreateScenarioReq) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateScenarioReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScenarioReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateScenarioResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScenarioResp) Reset() {
	*x = CreateScenarioResp{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScenarioResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScenarioResp) ProtoMessage() {}

func (x *CreateScenarioResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScenarioResp.ProtoReflect.Descriptor instead.
func (*CreateScenarioResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *CreateScenarioResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScenarioReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioReq) Reset() {
	*x = GetScenarioReq{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioReq) ProtoMessage() {}

func (x *GetScenarioReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioReq.ProtoReflect.Descriptor instead.
func (*GetScenarioReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *GetScenarioReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScenarioResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioResp) Reset() {
	*x = GetScenarioResp{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioResp) ProtoMessage() {}

func (x *GetScenarioResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioResp.ProtoReflect.Descriptor instead.
func (*GetScenarioResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *GetScenarioResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetScenarioResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetScenarioResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserProfileId string                 `protobuf:"bytes,2,opt,name=user_profile_id,json=userProfileId,proto3" json:"user_profile_id,omitempty"`
	ScenarioId    string                 `protobuf:"bytes,3,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionReq) Reset() {
	*x = CreateSessionReq{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionReq) ProtoMessage() {}

func (x *CreateSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionReq.ProtoReflect.Descriptor instead.
func (*CreateSessionReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSessionReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionReq) GetUserProfileId() string {
	if x != nil {
		return x.UserProfileId
	}
	return ""
}

func (x *CreateSessionReq) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type CreateSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResp) Reset() {
	*x = CreateSessionResp{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResp) ProtoMessage() {}

func (x *CreateSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResp.ProtoReflect.Descriptor instead.
func (*CreateSessionResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSessionResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSessionStatusReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EvaluationReport string                 `protobuf:"bytes,3,opt,name=evaluation_report,json=evaluationReport,proto3" json:"evaluation_report,omitempty"` // JSON
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateSessionStatusReq) Reset() {
	*x = UpdateSessionStatusReq{}
	mi := &file_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionStatusReq) ProtoMessage() {}

func (x *UpdateSessionStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateSessionStatusReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSessionStatusReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSessionStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateSessionStatusReq) GetEvaluationReport() string {
	if x != nil {
		return x.EvaluationReport
	}
	return ""
}

type UpdateSessionStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionStatusResp) Reset() {
	*x = UpdateSessionStatusResp{}
	mi := &file_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionStatusResp) ProtoMessage() {}

func (x *UpdateSessionStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateSessionStatusResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSessionStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddDialogueReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AudioObjectKey string                 `protobuf:"bytes,4,opt,name=audio_object_key,json=audioObjectKey,proto3" json:"audio_object_key,omitempty"` // 录音的 OSS key
	Evaluation     string                 `protobuf:"bytes,5,opt,name=evaluation,proto3" json:"evaluation,omitempty"`                                 // 此轮回答的 AI 评估报告 (JSON 格式文本)
	AudioContent   []byte                 `protobuf:"bytes,6,opt,name=audio_content,json=audioContent,proto3" json:"audio_content,omitempty"`         // 用户回答的完整 WAV 音频内容字节
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // 毫秒级时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddDialogueReq) Reset() {
	*x = AddDialogueReq{}
	mi := &file_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDialogueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogueReq) ProtoMessage() {}

func (x *AddDialogueReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogueReq.ProtoReflect.Descriptor instead.
func (*AddDialogueReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{14}
}

func (x *AddDialogueReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddDialogueReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddDialogueReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddDialogueReq) GetAudioObjectKey() string {
	if x != nil {
		return x.AudioObjectKey
	}
	return ""
}

func (x *AddDialogueReq) GetEvaluation() string {
	if x != nil {
		return x.Evaluation
	}
	return ""
}

func (x *AddDialogueReq) GetAudioContent() []byte {
	if x != nil {
		return x.AudioContent
	}
	return nil
}

func (x *AddDialogueReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AddDialogueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDialogueResp) Reset() {
	*x = AddDialogueResp{}
	mi := &file_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDialogueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogueResp) ProtoMessage() {}

func (x *AddDialogueResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogueResp.ProtoReflect.Descriptor instead.
func (*AddDialogueResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{15}
}

func (x *AddDialogueResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDialogueEvaluationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogueId    string                 `protobuf:"bytes,1,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	Evaluation    string                 `protobuf:"bytes,2,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDialogueEvaluationReq) Reset() {
	*x = UpdateDialogueEvaluationReq{}
	mi := &file_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDialogueEvaluationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDialogueEvaluationReq) ProtoMessage() {}

func (x *UpdateDialogueEvaluationReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDialogueEvaluationReq.ProtoReflect.Descriptor instead.
func (*UpdateDialogueEvaluationReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDialogueEvaluationReq) GetDialogueId() string {
	if x != nil {
		return x.DialogueId
	}
	return ""
}

func (x *UpdateDialogueEvaluationReq) GetEvaluation() string {
	if x != nil {
		return x.Evaluation
	}
	return ""
}

type UpdateDialogueEvaluationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDialogueEvaluationResp) Reset() {
	*x = UpdateDialogueEvaluationResp{}
	mi := &file_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDialogueEvaluationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDialogueEvaluationResp) ProtoMessage() {}

func (x *UpdateDialogueEvaluationResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDialogueEvaluationResp.ProtoReflect.Descriptor instead.
func (*UpdateDialogueEvaluationResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDialogueEvaluationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPracticeContextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPracticeContextReq) Reset() {
	*x = GetPracticeContextReq{}
	mi := &file_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPracticeContextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPracticeContextReq) ProtoMessage() {}

func (x *GetPracticeContextReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPracticeContextReq.ProtoReflect.Descriptor instead.
func (*GetPracticeContextReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{18}
}

func (x *GetPracticeContextReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetPracticeContextResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EnglishLevel   string                 `protobuf:"bytes,2,opt,name=english_level,json=englishLevel,proto3" json:"english_level,omitempty"`       // 英语水平
	LearningTarget string                 `protobuf:"bytes,3,opt,name=learning_target,json=learningTarget,proto3" json:"learning_target,omitempty"` // 学习目标
	ScenarioName   string                 `protobuf:"bytes,4,opt,name=scenario_name,json=scenarioName,proto3" json:"scenario_name,omitempty"`       // 场景名称
	ScenarioDesc   string                 `protobuf:"bytes,5,opt,name=scenario_desc,json=scenarioDesc,proto3" json:"scenario_desc,omitempty"`       // 场景描述
	UserId         string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用于后续 Token 额度扣减
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPracticeContextResp) Reset() {
	*x = GetPracticeContextResp{}
	mi := &file_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPracticeContextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPracticeContextResp) ProtoMessage() {}

func (x *GetPracticeContextResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPracticeContextResp.ProtoReflect.Descriptor instead.
func (*GetPracticeContextResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{19}
}

func (x *GetPracticeContextResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetPracticeContextResp) GetEnglishLevel() string {
	if x != nil {
		return x.EnglishLevel
	}
	return ""
}

func (x *GetPracticeContextResp) GetLearningTarget() string {
	if x != nil {
		return x.LearningTarget
	}
	return ""
}

func (x *GetPracticeContextResp) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *GetPracticeContextResp) GetScenarioDesc() string {
	if x != nil {
		return x.ScenarioDesc
	}
	return ""
}

func (x *GetPracticeContextResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListSessionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsReq) Reset() {
	*x = ListSessionsReq{}
	mi := &file_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsReq) ProtoMessage() {}

func (x *ListSessionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsReq.ProtoReflect.Descriptor instead.
func (*ListSessionsReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{20}
}

func (x *ListSessionsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SessionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ScenarioName  string                 `protobuf:"bytes,2,opt,name=scenario_name,json=scenarioName,proto3" json:"scenario_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OverallScore  int32                  `protobuf:"varint,5,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionItem) Reset() {
	*x = SessionItem{}
	mi := &file_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionItem) ProtoMessage() {}

func (x *SessionItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionItem.ProtoReflect.Descriptor instead.
func (*SessionItem) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{21}
}

func (x *SessionItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionItem) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *SessionItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionItem) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

type ListSessionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionItem         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResp) Reset() {
	*x = ListSessionsResp{}
	mi := &file_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResp) ProtoMessage() {}

func (x *ListSessionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResp.ProtoReflect.Descriptor instead.
func (*ListSessionsResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{22}
}

func (x *ListSessionsResp) GetSessions() []*SessionItem {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSessionDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionDetailReq) Reset() {
	*x = GetSessionDetailReq{}
	mi := &file_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionDetailReq) ProtoMessage() {}

func (x *GetSessionDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionDetailReq.ProtoReflect.Descriptor instead.
func (*GetSessionDetailReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{23}
}

func (x *GetSessionDetailReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionDetailResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ScenarioName     string                 `protobuf:"bytes,2,opt,name=scenario_name,json=scenarioName,proto3" json:"scenario_name,omitempty"`
	Transcript       string                 `protobuf:"bytes,3,opt,name=transcript,proto3" json:"transcript,omitempty"` // 格式化后的对话文本
	OverallScore     int32                  `protobuf:"varint,4,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	EvaluationReport string                 `protobuf:"bytes,5,opt,name=evaluation_report,json=evaluationReport,proto3" json:"evaluation_report,omitempty"` // JSON
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSessionDetailResp) Reset() {
	*x = GetSessionDetailResp{}
	mi := &file_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionDetailResp) ProtoMessage() {}

func (x *GetSessionDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionDetailResp.ProtoReflect.Descriptor instead.
func (*GetSessionDetailResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{24}
}

func (x *GetSessionDetailResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionDetailResp) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *GetSessionDetailResp) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *GetSessionDetailResp) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *GetSessionDetailResp) GetEvaluationReport() string {
	if x != nil {
		return x.EvaluationReport
	}
	return ""
}

type DeleteSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionReq) Reset() {
	*x = DeleteSessionReq{}
	mi := &file_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionReq) ProtoMessage() {}

func (x *DeleteSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionReq.ProtoReflect.Descriptor instead.
func (*DeleteSessionReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResp) Reset() {
	*x = DeleteSessionResp{}
	mi := &file_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResp) ProtoMessage() {}

func (x *DeleteSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResp.ProtoReflect.Descriptor instead.
func (*DeleteSessionResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteSessionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListUserProfilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserProfilesReq) Reset() {
	*x = ListUserProfilesReq{}
	mi := &file_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserProfilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserProfilesReq) ProtoMessage() {}

func (x *ListUserProfilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserProfilesReq.ProtoReflect.Descriptor instead.
func (*ListUserProfilesReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{27}
}

func (x *ListUserProfilesReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserProfileItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EnglishLevel   string                 `protobuf:"bytes,2,opt,name=english_level,json=englishLevel,proto3" json:"english_level,omitempty"`
	LearningTarget string                 `protobuf:"bytes,3,opt,name=learning_target,json=learningTarget,proto3" json:"learning_target,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserProfileItem) Reset() {
	*x = UserProfileItem{}
	mi := &file_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileItem) ProtoMessage() {}

func (x *UserProfileItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileItem.ProtoReflect.Descriptor instead.
func (*UserProfileItem) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{28}
}

func (x *UserProfileItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfileItem) GetEnglishLevel() string {
	if x != nil {
		return x.EnglishLevel
	}
	return ""
}

func (x *UserProfileItem) GetLearningTarget() string {
	if x != nil {
		return x.LearningTarget
	}
	return ""
}

func (x *UserProfileItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListUserProfilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*UserProfileItem     `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserProfilesResp) Reset() {
	*x = ListUserProfilesResp{}
	mi := &file_core_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserProfilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserProfilesResp) ProtoMessage() {}

func (x *ListUserProfilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserProfilesResp.ProtoReflect.Descriptor instead.
func (*ListUserProfilesResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{29}
}

func (x *ListUserProfilesResp) GetProfiles() []*UserProfileItem {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type ListScenariosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosReq) Reset() {
	*x = ListScenariosReq{}
	mi := &file_core_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosReq) ProtoMessage() {}

func (x *ListScenariosReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosReq.ProtoReflect.Descriptor instead.
func (*ListScenariosReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{30}
}

func (x *ListScenariosReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ScenarioItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatorId     string                 `protobuf:"bytes,4,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioItem) Reset() {
	*x = ScenarioItem{}
	mi := &file_core_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioItem) ProtoMessage() {}

func (x *ScenarioItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioItem.ProtoReflect.Descriptor instead.
func (*ScenarioItem) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{31}
}

func (x *ScenarioItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScenarioItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScenarioItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScenarioItem) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *ScenarioItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListScenariosResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*ScenarioItem        `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosResp) Reset() {
	*x = ListScenariosResp{}
	mi := &file_core_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosResp) ProtoMessage() {}

func (x *ListScenariosResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosResp.ProtoReflect.Descriptor instead.
func (*ListScenariosResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{32}
}

func (x *ListScenariosResp) GetScenarios() []*ScenarioItem {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04core\"2\n" +
	"\x14GenerateUploadUrlReq\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"U\n" +
	"\x15GenerateUploadUrlResp\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\"}\n" +
	"\x14CreateUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\renglish_level\x18\x02 \x01(\tR\fenglishLevel\x12'\n" +
	"\x0flearning_target\x18\x03 \x01(\tR\x0elearningTarget\"?\n" +
	"\x15CreateUserProfileResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"#\n" +
	"\x11GetUserProfileReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8b\x01\n" +
	"\x12GetUserProfileResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\renglish_level\x18\x03 \x01(\tR\fenglishLevel\x12'\n" +
	"\x0flearning_target\x18\x04 \x01(\tR\x0elearningTarget\"h\n" +
	"\x11CreateScenarioReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"$\n" +
	"\x12CreateScenarioResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eGetScenarioReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x0fGetScenarioResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"t\n" +
	"\x10CreateSessionReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0fuser_profile_id\x18\x02 \x01(\tR\ruserProfileId\x12\x1f\n" +
	"\vscenario_id\x18\x03 \x01(\tR\n" +
	"scenarioId\"#\n" +
	"\x11CreateSessionResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\x16UpdateSessionStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12+\n" +
	"\x11evaluation_report\x18\x03 \x01(\tR\x10evaluationReport\"3\n" +
	"\x17UpdateSessionStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xeb\x01\n" +
	"\x0eAddDialogueReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12(\n" +
	"\x10audio_object_key\x18\x04 \x01(\tR\x0eaudioObjectKey\x12\x1e\n" +
	"\n" +
	"evaluation\x18\x05 \x01(\tR\n" +
	"evaluation\x12#\n" +
	"\raudio_content\x18\x06 \x01(\fR\faudioContent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"!\n" +
	"\x0fAddDialogueResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x1bUpdateDialogueEvaluationReq\x12\x1f\n" +
	"\vdialogue_id\x18\x01 \x01(\tR\n" +
	"dialogueId\x12\x1e\n" +
	"\n" +
	"evaluation\x18\x02 \x01(\tR\n" +
	"evaluation\"8\n" +
	"\x1cUpdateDialogueEvaluationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	"\x15GetPracticeContextReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xe8\x01\n" +
	"\x16GetPracticeContextResp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\renglish_level\x18\x02 \x01(\tR\fenglishLevel\x12'\n" +
	"\x0flearning_target\x18\x03 \x01(\tR\x0elearningTarget\x12#\n" +
	"\rscenario_name\x18\x04 \x01(\tR\fscenarioName\x12#\n" +
	"\rscenario_desc\x18\x05 \x01(\tR\fscenarioDesc\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"*\n" +
	"\x0fListSessionsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9e\x01\n" +
	"\vSessionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rscenario_name\x18\x02 \x01(\tR\fscenarioName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12#\n" +
	"\roverall_score\x18\x05 \x01(\x05R\foverallScore\"A\n" +
	"\x10ListSessionsResp\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.core.SessionItemR\bsessions\"4\n" +
	"\x13GetSessionDetailReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xcc\x01\n" +
	"\x14GetSessionDetailResp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rscenario_name\x18\x02 \x01(\tR\fscenarioName\x12\x1e\n" +
	"\n" +
	"transcript\x18\x03 \x01(\tR\n" +
	"transcript\x12#\n" +
	"\roverall_score\x18\x04 \x01(\x05R\foverallScore\x12+\n" +
	"\x11evaluation_report\x18\x05 \x01(\tR\x10evaluationReport\"1\n" +
	"\x10DeleteSessionReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"-\n" +
	"\x11DeleteSessionResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x13ListUserProfilesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8e\x01\n" +
	"\x0fUserProfileItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\renglish_level\x18\x02 \x01(\tR\fenglishLevel\x12'\n" +
	"\x0flearning_target\x18\x03 \x01(\tR\x0elearningTarget\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"I\n" +
	"\x14ListUserProfilesResp\x121\n" +
	"\bprofiles\x18\x01 \x03(\v2\x15.core.UserProfileItemR\bprofiles\"+\n" +
	"\x10ListScenariosReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x92\x01\n" +
	"\fScenarioItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x04 \x01(\tR\tcreatorId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"E\n" +
	"\x11ListScenariosResp\x120\n" +
	"\tscenarios\x18\x01 \x03(\v2\x12.core.ScenarioItemR\tscenarios2\xc7\b\n" +
	"\x04Core\x12L\n" +
	"\x11GenerateUploadUrl\x12\x1a.core.GenerateUploadUrlReq\x1a\x1b.core.GenerateUploadUrlResp\x12L\n" +
	"\x11CreateUserProfile\x12\x1a.core.CreateUserProfileReq\x1a\x1b.core.CreateUserProfileResp\x12C\n" +
	"\x0eGetUserProfile\x12\x17.core.GetUserProfileReq\x1a\x18.core.GetUserProfileResp\x12C\n" +
	"\x0eCreateScenario\x12\x17.core.CreateScenarioReq\x1a\x18.core.CreateScenarioResp\x12:\n" +
	"\vGetScenario\x12\x14.core.GetScenarioReq\x1a\x15.core.GetScenarioResp\x12@\n" +
	"\rCreateSession\x12\x16.core.CreateSessionReq\x1a\x17.core.CreateSessionResp\x12R\n" +
	"\x13UpdateSessionStatus\x12\x1c.core.UpdateSessionStatusReq\x1a\x1d.core.UpdateSessionStatusResp\x12:\n" +
	"\vAddDialogue\x12\x14.core.AddDialogueReq\x1a\x15.core.AddDialogueResp\x12a\n" +
	"\x18UpdateDialogueEvaluation\x12!.core.UpdateDialogueEvaluationReq\x1a\".core.UpdateDialogueEvaluationResp\x12O\n" +
	"\x12GetPracticeContext\x12\x1b.core.GetPracticeContextReq\x1a\x1c.core.GetPracticeContextResp\x12=\n" +
	"\fListSessions\x12\x15.core.ListSessionsReq\x1a\x16.core.ListSessionsResp\x12I\n" +
	"\x10GetSessionDetail\x12\x19.core.GetSessionDetailReq\x1a\x1a.core.GetSessionDetailResp\x12@\n" +
	"\rDeleteSession\x12\x16.core.DeleteSessionReq\x1a\x17.core.DeleteSessionResp\x12I\n" +
	"\x10ListUserProfiles\x12\x19.core.ListUserProfilesReq\x1a\x1a.core.ListUserProfilesResp\x12@\n" +
	"\rListScenarios\x12\x16.core.ListScenariosReq\x1a\x17.core.ListScenariosRespB\bZ\x06./coreb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_core_proto_goTypes = []any{
	(*GenerateUploadUrlReq)(nil),         // 0: core.GenerateUploadUrlReq
	(*GenerateUploadUrlResp)(nil),        // 1: core.GenerateUploadUrlResp
	(*CreateUserProfileReq)(nil),         // 2: core.CreateUserProfileReq
	(*CreateUserProfileResp)(nil),        // 3: core.CreateUserProfileResp
	(*GetUserProfileReq)(nil),            // 4: core.GetUserProfileReq
	(*GetUserProfileResp)(nil),           // 5: core.GetUserProfileResp
	(*CreateScenarioReq)(nil),            // 6: core.CreateScenarioReq
	(*CreateScenarioResp)(nil),           // 7: core.CreateScenarioResp
	(*GetScenarioReq)(nil),               // 8: core.GetScenarioReq
	(*GetScenarioResp)(nil),              // 9: core.GetScenarioResp
	(*CreateSessionReq)(nil),             // 10: core.CreateSessionReq
	(*CreateSessionResp)(nil),            // 11: core.CreateSessionResp
	(*UpdateSessionStatusReq)(nil),       // 12: core.UpdateSessionStatusReq
	(*UpdateSessionStatusResp)(nil),      // 13: core.UpdateSessionStatusResp
	(*AddDialogueReq)(nil),               // 14: core.AddDialogueReq
	(*AddDialogueResp)(nil),              // 15: core.AddDialogueResp
	(*UpdateDialogueEvaluationReq)(nil),  // 16: core.UpdateDialogueEvaluationReq
	(*UpdateDialogueEvaluationResp)(nil), // 17: core.UpdateDialogueEvaluationResp
	(*GetPracticeContextReq)(nil),        // 18: core.GetPracticeContextReq
	(*GetPracticeContextResp)(nil),       // 19: core.GetPracticeContextResp
	(*ListSessionsReq)(nil),              // 20: core.ListSessionsReq
	(*SessionItem)(nil),                  // 21: core.SessionItem
	(*ListSessionsResp)(nil),             // 22: core.ListSessionsResp
	(*GetSessionDetailReq)(nil),          // 23: core.GetSessionDetailReq
	(*GetSessionDetailResp)(nil),         // 24: core.GetSessionDetailResp
	(*DeleteSessionReq)(nil),             // 25: core.DeleteSessionReq
	(*DeleteSessionResp)(nil),            // 26: core.DeleteSessionResp
	(*ListUserProfilesReq)(nil),          // 27: core.ListUserProfilesReq
	(*UserProfileItem)(nil),              // 28: core.UserProfileItem
	(*ListUserProfilesResp)(nil),         // 29: core.ListUserProfilesResp
	(*ListScenariosReq)(nil),             // 30: core.ListScenariosReq
	(*ScenarioItem)(nil),                 // 31: core.ScenarioItem
	(*ListScenariosResp)(nil),            // 32: core.ListScenariosResp
}
var file_core_proto_depIdxs = []int32{
	21, // 0: core.ListSessionsResp.sessions:type_name -> core.SessionItem
	28, // 1: core.ListUserProfilesResp.profiles:type_name -> core.UserProfileItem
	31, // 2: core.ListScenariosResp.scenarios:type_name -> core.ScenarioItem
	0,  // 3: core.Core.GenerateUploadUrl:input_type -> core.GenerateUploadUrlReq
	2,  // 4: core.Core.CreateUserProfile:input_type -> core.CreateUserProfileReq
	4,  // 5: core.Core.GetUserProfile:input_type -> core.GetUserProfileReq
	6,  // 6: core.Core.CreateScenario:input_type -> core.CreateScenarioReq
	8,  // 7: core.Core.GetScenario:input_type -> core.GetScenarioReq
	10, // 8: core.Core.CreateSession:input_type -> core.CreateSessionReq
	12, // 9: core.Core.UpdateSessionStatus:input_type -> core.UpdateSessionStatusReq
	14, // 10: core.Core.AddDialogue:input_type -> core.AddDialogueReq
	16, // 11: core.Core.UpdateDialogueEvaluation:input_type -> core.UpdateDialogueEvaluationReq
	18, // 12: core.Core.GetPracticeContext:input_type -> core.GetPracticeContextReq
	20, // 13: core.Core.ListSessions:input_type -> core.ListSessionsReq
	23, // 14: core.Core.GetSessionDetail:input_type -> core.GetSessionDetailReq
	25, // 15: core.Core.DeleteSession:input_type -> core.DeleteSessionReq
	27, // 16: core.Core.ListUserProfiles:input_type -> core.ListUserProfilesReq
	30, // 17: core.Core.ListScenarios:input_type -> core.ListScenariosReq
	1,  // 18: core.Core.GenerateUploadUrl:output_type -> core.GenerateUploadUrlResp
	3,  // 19: core.Core.CreateUserProfile:output_type -> core.CreateUserProfileResp
	5,  // 20: core.Core.GetUserProfile:output_type -> core.GetUserProfileResp
	7,  // 21: core.Core.CreateScenario:output_type -> core.CreateScenarioResp
	9,  // 22: core.Core.GetScenario:output_type -> core.GetScenarioResp
	11, // 23: core.Core.CreateSession:output_type -> core.CreateSessionResp
	13, // 24: core.Core.UpdateSessionStatus:output_type -> core.UpdateSessionStatusResp
	15, // 25: core.Core.AddDialogue:output_type -> core.AddDialogueResp
	17, // 26: core.Core.UpdateDialogueEvaluation:output_type -> core.UpdateDialogueEvaluationResp
	19, // 27: core.Core.GetPracticeContext:output_type -> core.GetPracticeContextResp
	22, // 28: core.Core.ListSessions:output_type -> core.ListSessionsResp
	24, // 29: core.Core.GetSessionDetail:output_type -> core.GetSessionDetailResp
	26, // 30: core.Core.DeleteSession:output_type -> core.DeleteSessionResp
	29, // 31: core.Core.ListUserProfiles:output_type -> core.ListUserProfilesResp
	32, // 32: core.Core.ListScenarios:output_type -> core.ListScenariosResp
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
