// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateUploadUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadUrlReq) Reset() {
	*x = GenerateUploadUrlReq{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadUrlReq) ProtoMessage() {}

func (x *GenerateUploadUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadUrlReq.ProtoReflect.Descriptor instead.
func (*GenerateUploadUrlReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateUploadUrlReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type GenerateUploadUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // 预签名 PUT URL
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // 后续落库用的 OSS Key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadUrlResp) Reset() {
	*x = GenerateUploadUrlResp{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadUrlResp) ProtoMessage() {}

func (x *GenerateUploadUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadUrlResp.ProtoReflect.Descriptor instead.
func (*GenerateUploadUrlResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateUploadUrlResp) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GenerateUploadUrlResp) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type CreateResumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // OSS 中的文件路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResumeReq) Reset() {
	*x = CreateResumeReq{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeReq) ProtoMessage() {}

func (x *CreateResumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeReq.ProtoReflect.Descriptor instead.
func (*CreateResumeReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResumeReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateResumeReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type CreateResumeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 解析状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResumeResp) Reset() {
	*x = CreateResumeResp{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResumeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeResp) ProtoMessage() {}

func (x *CreateResumeResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeResp.ProtoReflect.Descriptor instead.
func (*CreateResumeResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResumeResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateResumeResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetResumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeReq) Reset() {
	*x = GetResumeReq{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeReq) ProtoMessage() {}

func (x *GetResumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeReq.ProtoReflect.Descriptor instead.
func (*GetResumeReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *GetResumeReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResumeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`             // JSON 格式
	PdfUrl        string                 `protobuf:"bytes,4,opt,name=pdf_url,json=pdfUrl,proto3" json:"pdf_url,omitempty"` // 预签名 GET URL (带时效)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeResp) Reset() {
	*x = GetResumeResp{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeResp) ProtoMessage() {}

func (x *GetResumeResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeResp.ProtoReflect.Descriptor instead.
func (*GetResumeResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *GetResumeResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResumeResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetResumeResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetResumeResp) GetPdfUrl() string {
	if x != nil {
		return x.PdfUrl
	}
	return ""
}

type CreateJobProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobProfileReq) Reset() {
	*x = CreateJobProfileReq{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobProfileReq) ProtoMessage() {}

func (x *CreateJobProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobProfileReq.ProtoReflect.Descriptor instead.
func (*CreateJobProfileReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *CreateJobProfileReq) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateJobProfileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateJobProfileReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateJobProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobProfileResp) Reset() {
	*x = CreateJobProfileResp{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobProfileResp) ProtoMessage() {}

func (x *CreateJobProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobProfileResp.ProtoReflect.Descriptor instead.
func (*CreateJobProfileResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *CreateJobProfileResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobProfileReq) Reset() {
	*x = GetJobProfileReq{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobProfileReq) ProtoMessage() {}

func (x *GetJobProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobProfileReq.ProtoReflect.Descriptor instead.
func (*GetJobProfileReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobProfileReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobProfileResp) Reset() {
	*x = GetJobProfileResp{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobProfileResp) ProtoMessage() {}

func (x *GetJobProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobProfileResp.ProtoReflect.Descriptor instead.
func (*GetJobProfileResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *GetJobProfileResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetJobProfileResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetJobProfileResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResumeId      string                 `protobuf:"bytes,2,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	JobProfileId  string                 `protobuf:"bytes,3,opt,name=job_profile_id,json=jobProfileId,proto3" json:"job_profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionReq) Reset() {
	*x = CreateSessionReq{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionReq) ProtoMessage() {}

func (x *CreateSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionReq.ProtoReflect.Descriptor instead.
func (*CreateSessionReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSessionReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionReq) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *CreateSessionReq) GetJobProfileId() string {
	if x != nil {
		return x.JobProfileId
	}
	return ""
}

type CreateSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResp) Reset() {
	*x = CreateSessionResp{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResp) ProtoMessage() {}

func (x *CreateSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResp.ProtoReflect.Descriptor instead.
func (*CreateSessionResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSessionResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSessionStatusReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EvaluationReport string                 `protobuf:"bytes,3,opt,name=evaluation_report,json=evaluationReport,proto3" json:"evaluation_report,omitempty"` // JSON
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateSessionStatusReq) Reset() {
	*x = UpdateSessionStatusReq{}
	mi := &file_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionStatusReq) ProtoMessage() {}

func (x *UpdateSessionStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateSessionStatusReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSessionStatusReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSessionStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateSessionStatusReq) GetEvaluationReport() string {
	if x != nil {
		return x.EvaluationReport
	}
	return ""
}

type UpdateSessionStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionStatusResp) Reset() {
	*x = UpdateSessionStatusResp{}
	mi := &file_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionStatusResp) ProtoMessage() {}

func (x *UpdateSessionStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateSessionStatusResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSessionStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddDialogueReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AudioObjectKey string                 `protobuf:"bytes,4,opt,name=audio_object_key,json=audioObjectKey,proto3" json:"audio_object_key,omitempty"` // 录音的 OSS key
	Evaluation     string                 `protobuf:"bytes,5,opt,name=evaluation,proto3" json:"evaluation,omitempty"`                                 // 此轮回答的 AI 评估报告 (JSON 格式文本)
	AudioContent   []byte                 `protobuf:"bytes,6,opt,name=audio_content,json=audioContent,proto3" json:"audio_content,omitempty"`         // 用户回答的完整 WAV 音频内容字节
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddDialogueReq) Reset() {
	*x = AddDialogueReq{}
	mi := &file_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDialogueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogueReq) ProtoMessage() {}

func (x *AddDialogueReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogueReq.ProtoReflect.Descriptor instead.
func (*AddDialogueReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{14}
}

func (x *AddDialogueReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddDialogueReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddDialogueReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddDialogueReq) GetAudioObjectKey() string {
	if x != nil {
		return x.AudioObjectKey
	}
	return ""
}

func (x *AddDialogueReq) GetEvaluation() string {
	if x != nil {
		return x.Evaluation
	}
	return ""
}

func (x *AddDialogueReq) GetAudioContent() []byte {
	if x != nil {
		return x.AudioContent
	}
	return nil
}

type AddDialogueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDialogueResp) Reset() {
	*x = AddDialogueResp{}
	mi := &file_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDialogueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogueResp) ProtoMessage() {}

func (x *AddDialogueResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogueResp.ProtoReflect.Descriptor instead.
func (*AddDialogueResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{15}
}

func (x *AddDialogueResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDialogueEvaluationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogueId    string                 `protobuf:"bytes,1,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	Evaluation    string                 `protobuf:"bytes,2,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDialogueEvaluationReq) Reset() {
	*x = UpdateDialogueEvaluationReq{}
	mi := &file_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDialogueEvaluationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDialogueEvaluationReq) ProtoMessage() {}

func (x *UpdateDialogueEvaluationReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDialogueEvaluationReq.ProtoReflect.Descriptor instead.
func (*UpdateDialogueEvaluationReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDialogueEvaluationReq) GetDialogueId() string {
	if x != nil {
		return x.DialogueId
	}
	return ""
}

func (x *UpdateDialogueEvaluationReq) GetEvaluation() string {
	if x != nil {
		return x.Evaluation
	}
	return ""
}

type UpdateDialogueEvaluationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDialogueEvaluationResp) Reset() {
	*x = UpdateDialogueEvaluationResp{}
	mi := &file_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDialogueEvaluationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDialogueEvaluationResp) ProtoMessage() {}

func (x *UpdateDialogueEvaluationResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDialogueEvaluationResp.ProtoReflect.Descriptor instead.
func (*UpdateDialogueEvaluationResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDialogueEvaluationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 一次性拉取面试所需的完整上下文
// interview_api 在建立 WebSocket 后，用 session_id 调用此接口获取简历和岗位信息
// 用于组装发给 Gemini Live API 的系统提示词
type GetInterviewContextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterviewContextReq) Reset() {
	*x = GetInterviewContextReq{}
	mi := &file_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterviewContextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterviewContextReq) ProtoMessage() {}

func (x *GetInterviewContextReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterviewContextReq.ProtoReflect.Descriptor instead.
func (*GetInterviewContextReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{18}
}

func (x *GetInterviewContextReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetInterviewContextResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ResumeContent  string                 `protobuf:"bytes,2,opt,name=resume_content,json=resumeContent,proto3" json:"resume_content,omitempty"`      // 简历结构化 JSON
	JobProfileName string                 `protobuf:"bytes,3,opt,name=job_profile_name,json=jobProfileName,proto3" json:"job_profile_name,omitempty"` // 岗位名称
	JobProfileDesc string                 `protobuf:"bytes,4,opt,name=job_profile_desc,json=jobProfileDesc,proto3" json:"job_profile_desc,omitempty"` // 岗位描述
	UserId         string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                           // 用于后续 Token 额度扣减
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInterviewContextResp) Reset() {
	*x = GetInterviewContextResp{}
	mi := &file_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterviewContextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterviewContextResp) ProtoMessage() {}

func (x *GetInterviewContextResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterviewContextResp.ProtoReflect.Descriptor instead.
func (*GetInterviewContextResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{19}
}

func (x *GetInterviewContextResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetInterviewContextResp) GetResumeContent() string {
	if x != nil {
		return x.ResumeContent
	}
	return ""
}

func (x *GetInterviewContextResp) GetJobProfileName() string {
	if x != nil {
		return x.JobProfileName
	}
	return ""
}

func (x *GetInterviewContextResp) GetJobProfileDesc() string {
	if x != nil {
		return x.JobProfileDesc
	}
	return ""
}

func (x *GetInterviewContextResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListSessionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsReq) Reset() {
	*x = ListSessionsReq{}
	mi := &file_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsReq) ProtoMessage() {}

func (x *ListSessionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsReq.ProtoReflect.Descriptor instead.
func (*ListSessionsReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{20}
}

func (x *ListSessionsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SessionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobTitle      string                 `protobuf:"bytes,2,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OverallScore  int32                  `protobuf:"varint,5,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionItem) Reset() {
	*x = SessionItem{}
	mi := &file_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionItem) ProtoMessage() {}

func (x *SessionItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionItem.ProtoReflect.Descriptor instead.
func (*SessionItem) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{21}
}

func (x *SessionItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionItem) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *SessionItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionItem) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

type ListSessionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionItem         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResp) Reset() {
	*x = ListSessionsResp{}
	mi := &file_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResp) ProtoMessage() {}

func (x *ListSessionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResp.ProtoReflect.Descriptor instead.
func (*ListSessionsResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{22}
}

func (x *ListSessionsResp) GetSessions() []*SessionItem {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSessionDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionDetailReq) Reset() {
	*x = GetSessionDetailReq{}
	mi := &file_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionDetailReq) ProtoMessage() {}

func (x *GetSessionDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionDetailReq.ProtoReflect.Descriptor instead.
func (*GetSessionDetailReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{23}
}

func (x *GetSessionDetailReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionDetailResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	JobTitle         string                 `protobuf:"bytes,2,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Transcript       string                 `protobuf:"bytes,3,opt,name=transcript,proto3" json:"transcript,omitempty"` // 格式化后的对话文本
	OverallScore     int32                  `protobuf:"varint,4,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	EvaluationReport string                 `protobuf:"bytes,5,opt,name=evaluation_report,json=evaluationReport,proto3" json:"evaluation_report,omitempty"` // JSON
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSessionDetailResp) Reset() {
	*x = GetSessionDetailResp{}
	mi := &file_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionDetailResp) ProtoMessage() {}

func (x *GetSessionDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionDetailResp.ProtoReflect.Descriptor instead.
func (*GetSessionDetailResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{24}
}

func (x *GetSessionDetailResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionDetailResp) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *GetSessionDetailResp) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *GetSessionDetailResp) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *GetSessionDetailResp) GetEvaluationReport() string {
	if x != nil {
		return x.EvaluationReport
	}
	return ""
}

type DeleteSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionReq) Reset() {
	*x = DeleteSessionReq{}
	mi := &file_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionReq) ProtoMessage() {}

func (x *DeleteSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionReq.ProtoReflect.Descriptor instead.
func (*DeleteSessionReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResp) Reset() {
	*x = DeleteSessionResp{}
	mi := &file_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResp) ProtoMessage() {}

func (x *DeleteSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResp.ProtoReflect.Descriptor instead.
func (*DeleteSessionResp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteSessionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04core\"2\n" +
	"\x14GenerateUploadUrlReq\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"U\n" +
	"\x15GenerateUploadUrlResp\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\"I\n" +
	"\x0fCreateResumeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\":\n" +
	"\x10CreateResumeResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x1e\n" +
	"\fGetResumeReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"k\n" +
	"\rGetResumeResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\apdf_url\x18\x04 \x01(\tR\x06pdfUrl\"j\n" +
	"\x13CreateJobProfileReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"&\n" +
	"\x14CreateJobProfileResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10GetJobProfileReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x11GetJobProfileResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"n\n" +
	"\x10CreateSessionReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tresume_id\x18\x02 \x01(\tR\bresumeId\x12$\n" +
	"\x0ejob_profile_id\x18\x03 \x01(\tR\fjobProfileId\"#\n" +
	"\x11CreateSessionResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\x16UpdateSessionStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12+\n" +
	"\x11evaluation_report\x18\x03 \x01(\tR\x10evaluationReport\"3\n" +
	"\x17UpdateSessionStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcc\x01\n" +
	"\x0eAddDialogueReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12(\n" +
	"\x10audio_object_key\x18\x04 \x01(\tR\x0eaudioObjectKey\x12\x1e\n" +
	"\n" +
	"evaluation\x18\x05 \x01(\tR\n" +
	"evaluation\x12#\n" +
	"\raudio_content\x18\x06 \x01(\fR\faudioContent\"!\n" +
	"\x0fAddDialogueResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x1bUpdateDialogueEvaluationReq\x12\x1f\n" +
	"\vdialogue_id\x18\x01 \x01(\tR\n" +
	"dialogueId\x12\x1e\n" +
	"\n" +
	"evaluation\x18\x02 \x01(\tR\n" +
	"evaluation\"8\n" +
	"\x1cUpdateDialogueEvaluationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x16GetInterviewContextReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xcc\x01\n" +
	"\x17GetInterviewContextResp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eresume_content\x18\x02 \x01(\tR\rresumeContent\x12(\n" +
	"\x10job_profile_name\x18\x03 \x01(\tR\x0ejobProfileName\x12(\n" +
	"\x10job_profile_desc\x18\x04 \x01(\tR\x0ejobProfileDesc\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"*\n" +
	"\x0fListSessionsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x96\x01\n" +
	"\vSessionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tjob_title\x18\x02 \x01(\tR\bjobTitle\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12#\n" +
	"\roverall_score\x18\x05 \x01(\x05R\foverallScore\"A\n" +
	"\x10ListSessionsResp\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.core.SessionItemR\bsessions\"4\n" +
	"\x13GetSessionDetailReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc4\x01\n" +
	"\x14GetSessionDetailResp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tjob_title\x18\x02 \x01(\tR\bjobTitle\x12\x1e\n" +
	"\n" +
	"transcript\x18\x03 \x01(\tR\n" +
	"transcript\x12#\n" +
	"\roverall_score\x18\x04 \x01(\x05R\foverallScore\x12+\n" +
	"\x11evaluation_report\x18\x05 \x01(\tR\x10evaluationReport\"1\n" +
	"\x10DeleteSessionReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"-\n" +
	"\x11DeleteSessionResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xab\a\n" +
	"\x04Core\x12L\n" +
	"\x11GenerateUploadUrl\x12\x1a.core.GenerateUploadUrlReq\x1a\x1b.core.GenerateUploadUrlResp\x12=\n" +
	"\fCreateResume\x12\x15.core.CreateResumeReq\x1a\x16.core.CreateResumeResp\x124\n" +
	"\tGetResume\x12\x12.core.GetResumeReq\x1a\x13.core.GetResumeResp\x12I\n" +
	"\x10CreateJobProfile\x12\x19.core.CreateJobProfileReq\x1a\x1a.core.CreateJobProfileResp\x12@\n" +
	"\rGetJobProfile\x12\x16.core.GetJobProfileReq\x1a\x17.core.GetJobProfileResp\x12@\n" +
	"\rCreateSession\x12\x16.core.CreateSessionReq\x1a\x17.core.CreateSessionResp\x12R\n" +
	"\x13UpdateSessionStatus\x12\x1c.core.UpdateSessionStatusReq\x1a\x1d.core.UpdateSessionStatusResp\x12:\n" +
	"\vAddDialogue\x12\x14.core.AddDialogueReq\x1a\x15.core.AddDialogueResp\x12a\n" +
	"\x18UpdateDialogueEvaluation\x12!.core.UpdateDialogueEvaluationReq\x1a\".core.UpdateDialogueEvaluationResp\x12R\n" +
	"\x13GetInterviewContext\x12\x1c.core.GetInterviewContextReq\x1a\x1d.core.GetInterviewContextResp\x12=\n" +
	"\fListSessions\x12\x15.core.ListSessionsReq\x1a\x16.core.ListSessionsResp\x12I\n" +
	"\x10GetSessionDetail\x12\x19.core.GetSessionDetailReq\x1a\x1a.core.GetSessionDetailResp\x12@\n" +
	"\rDeleteSession\x12\x16.core.DeleteSessionReq\x1a\x17.core.DeleteSessionRespB\bZ\x06./coreb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_core_proto_goTypes = []any{
	(*GenerateUploadUrlReq)(nil),         // 0: core.GenerateUploadUrlReq
	(*GenerateUploadUrlResp)(nil),        // 1: core.GenerateUploadUrlResp
	(*CreateResumeReq)(nil),              // 2: core.CreateResumeReq
	(*CreateResumeResp)(nil),             // 3: core.CreateResumeResp
	(*GetResumeReq)(nil),                 // 4: core.GetResumeReq
	(*GetResumeResp)(nil),                // 5: core.GetResumeResp
	(*CreateJobProfileReq)(nil),          // 6: core.CreateJobProfileReq
	(*CreateJobProfileResp)(nil),         // 7: core.CreateJobProfileResp
	(*GetJobProfileReq)(nil),             // 8: core.GetJobProfileReq
	(*GetJobProfileResp)(nil),            // 9: core.GetJobProfileResp
	(*CreateSessionReq)(nil),             // 10: core.CreateSessionReq
	(*CreateSessionResp)(nil),            // 11: core.CreateSessionResp
	(*UpdateSessionStatusReq)(nil),       // 12: core.UpdateSessionStatusReq
	(*UpdateSessionStatusResp)(nil),      // 13: core.UpdateSessionStatusResp
	(*AddDialogueReq)(nil),               // 14: core.AddDialogueReq
	(*AddDialogueResp)(nil),              // 15: core.AddDialogueResp
	(*UpdateDialogueEvaluationReq)(nil),  // 16: core.UpdateDialogueEvaluationReq
	(*UpdateDialogueEvaluationResp)(nil), // 17: core.UpdateDialogueEvaluationResp
	(*GetInterviewContextReq)(nil),       // 18: core.GetInterviewContextReq
	(*GetInterviewContextResp)(nil),      // 19: core.GetInterviewContextResp
	(*ListSessionsReq)(nil),              // 20: core.ListSessionsReq
	(*SessionItem)(nil),                  // 21: core.SessionItem
	(*ListSessionsResp)(nil),             // 22: core.ListSessionsResp
	(*GetSessionDetailReq)(nil),          // 23: core.GetSessionDetailReq
	(*GetSessionDetailResp)(nil),         // 24: core.GetSessionDetailResp
	(*DeleteSessionReq)(nil),             // 25: core.DeleteSessionReq
	(*DeleteSessionResp)(nil),            // 26: core.DeleteSessionResp
}
var file_core_proto_depIdxs = []int32{
	21, // 0: core.ListSessionsResp.sessions:type_name -> core.SessionItem
	0,  // 1: core.Core.GenerateUploadUrl:input_type -> core.GenerateUploadUrlReq
	2,  // 2: core.Core.CreateResume:input_type -> core.CreateResumeReq
	4,  // 3: core.Core.GetResume:input_type -> core.GetResumeReq
	6,  // 4: core.Core.CreateJobProfile:input_type -> core.CreateJobProfileReq
	8,  // 5: core.Core.GetJobProfile:input_type -> core.GetJobProfileReq
	10, // 6: core.Core.CreateSession:input_type -> core.CreateSessionReq
	12, // 7: core.Core.UpdateSessionStatus:input_type -> core.UpdateSessionStatusReq
	14, // 8: core.Core.AddDialogue:input_type -> core.AddDialogueReq
	16, // 9: core.Core.UpdateDialogueEvaluation:input_type -> core.UpdateDialogueEvaluationReq
	18, // 10: core.Core.GetInterviewContext:input_type -> core.GetInterviewContextReq
	20, // 11: core.Core.ListSessions:input_type -> core.ListSessionsReq
	23, // 12: core.Core.GetSessionDetail:input_type -> core.GetSessionDetailReq
	25, // 13: core.Core.DeleteSession:input_type -> core.DeleteSessionReq
	1,  // 14: core.Core.GenerateUploadUrl:output_type -> core.GenerateUploadUrlResp
	3,  // 15: core.Core.CreateResume:output_type -> core.CreateResumeResp
	5,  // 16: core.Core.GetResume:output_type -> core.GetResumeResp
	7,  // 17: core.Core.CreateJobProfile:output_type -> core.CreateJobProfileResp
	9,  // 18: core.Core.GetJobProfile:output_type -> core.GetJobProfileResp
	11, // 19: core.Core.CreateSession:output_type -> core.CreateSessionResp
	13, // 20: core.Core.UpdateSessionStatus:output_type -> core.UpdateSessionStatusResp
	15, // 21: core.Core.AddDialogue:output_type -> core.AddDialogueResp
	17, // 22: core.Core.UpdateDialogueEvaluation:output_type -> core.UpdateDialogueEvaluationResp
	19, // 23: core.Core.GetInterviewContext:output_type -> core.GetInterviewContextResp
	22, // 24: core.Core.ListSessions:output_type -> core.ListSessionsResp
	24, // 25: core.Core.GetSessionDetail:output_type -> core.GetSessionDetailResp
	26, // 26: core.Core.DeleteSession:output_type -> core.DeleteSessionResp
	14, // [14:27] is the sub-list for method output_type
	1,  // [1:14] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
