// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Core_GenerateUploadUrl_FullMethodName        = "/core.Core/GenerateUploadUrl"
	Core_CreateUserProfile_FullMethodName        = "/core.Core/CreateUserProfile"
	Core_GetUserProfile_FullMethodName           = "/core.Core/GetUserProfile"
	Core_CreateScenario_FullMethodName           = "/core.Core/CreateScenario"
	Core_GetScenario_FullMethodName              = "/core.Core/GetScenario"
	Core_CreateSession_FullMethodName            = "/core.Core/CreateSession"
	Core_UpdateSessionStatus_FullMethodName      = "/core.Core/UpdateSessionStatus"
	Core_AddDialogue_FullMethodName              = "/core.Core/AddDialogue"
	Core_UpdateDialogueEvaluation_FullMethodName = "/core.Core/UpdateDialogueEvaluation"
	Core_GetPracticeContext_FullMethodName       = "/core.Core/GetPracticeContext"
	Core_ListSessions_FullMethodName             = "/core.Core/ListSessions"
	Core_GetSessionDetail_FullMethodName         = "/core.Core/GetSessionDetail"
	Core_DeleteSession_FullMethodName            = "/core.Core/DeleteSession"
	Core_ListUserProfiles_FullMethodName         = "/core.Core/ListUserProfiles"
	Core_ListScenarios_FullMethodName            = "/core.Core/ListScenarios"
)

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreClient interface {
	// User Profile & OSS
	GenerateUploadUrl(ctx context.Context, in *GenerateUploadUrlReq, opts ...grpc.CallOption) (*GenerateUploadUrlResp, error)
	CreateUserProfile(ctx context.Context, in *CreateUserProfileReq, opts ...grpc.CallOption) (*CreateUserProfileResp, error)
	GetUserProfile(ctx context.Context, in *GetUserProfileReq, opts ...grpc.CallOption) (*GetUserProfileResp, error)
	// Scenarios
	CreateScenario(ctx context.Context, in *CreateScenarioReq, opts ...grpc.CallOption) (*CreateScenarioResp, error)
	GetScenario(ctx context.Context, in *GetScenarioReq, opts ...grpc.CallOption) (*GetScenarioResp, error)
	// Practice Sessions
	CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error)
	UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error)
	// Dialogues
	AddDialogue(ctx context.Context, in *AddDialogueReq, opts ...grpc.CallOption) (*AddDialogueResp, error)
	UpdateDialogueEvaluation(ctx context.Context, in *UpdateDialogueEvaluationReq, opts ...grpc.CallOption) (*UpdateDialogueEvaluationResp, error)
	// 上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
	GetPracticeContext(ctx context.Context, in *GetPracticeContextReq, opts ...grpc.CallOption) (*GetPracticeContextResp, error)
	// 列表与详情
	ListSessions(ctx context.Context, in *ListSessionsReq, opts ...grpc.CallOption) (*ListSessionsResp, error)
	GetSessionDetail(ctx context.Context, in *GetSessionDetailReq, opts ...grpc.CallOption) (*GetSessionDetailResp, error)
	DeleteSession(ctx context.Context, in *DeleteSessionReq, opts ...grpc.CallOption) (*DeleteSessionResp, error)
	ListUserProfiles(ctx context.Context, in *ListUserProfilesReq, opts ...grpc.CallOption) (*ListUserProfilesResp, error)
	ListScenarios(ctx context.Context, in *ListScenariosReq, opts ...grpc.CallOption) (*ListScenariosResp, error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) GenerateUploadUrl(ctx context.Context, in *GenerateUploadUrlReq, opts ...grpc.CallOption) (*GenerateUploadUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateUploadUrlResp)
	err := c.cc.Invoke(ctx, Core_GenerateUploadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateUserProfile(ctx context.Context, in *CreateUserProfileReq, opts ...grpc.CallOption) (*CreateUserProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserProfileResp)
	err := c.cc.Invoke(ctx, Core_CreateUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetUserProfile(ctx context.Context, in *GetUserProfileReq, opts ...grpc.CallOption) (*GetUserProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResp)
	err := c.cc.Invoke(ctx, Core_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateScenario(ctx context.Context, in *CreateScenarioReq, opts ...grpc.CallOption) (*CreateScenarioResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScenarioResp)
	err := c.cc.Invoke(ctx, Core_CreateScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetScenario(ctx context.Context, in *GetScenarioReq, opts ...grpc.CallOption) (*GetScenarioResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScenarioResp)
	err := c.cc.Invoke(ctx, Core_GetScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResp)
	err := c.cc.Invoke(ctx, Core_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionStatusResp)
	err := c.cc.Invoke(ctx, Core_UpdateSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) AddDialogue(ctx context.Context, in *AddDialogueReq, opts ...grpc.CallOption) (*AddDialogueResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDialogueResp)
	err := c.cc.Invoke(ctx, Core_AddDialogue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpdateDialogueEvaluation(ctx context.Context, in *UpdateDialogueEvaluationReq, opts ...grpc.CallOption) (*UpdateDialogueEvaluationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDialogueEvaluationResp)
	err := c.cc.Invoke(ctx, Core_UpdateDialogueEvaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetPracticeContext(ctx context.Context, in *GetPracticeContextReq, opts ...grpc.CallOption) (*GetPracticeContextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPracticeContextResp)
	err := c.cc.Invoke(ctx, Core_GetPracticeContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ListSessions(ctx context.Context, in *ListSessionsReq, opts ...grpc.CallOption) (*ListSessionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResp)
	err := c.cc.Invoke(ctx, Core_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetSessionDetail(ctx context.Context, in *GetSessionDetailReq, opts ...grpc.CallOption) (*GetSessionDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionDetailResp)
	err := c.cc.Invoke(ctx, Core_GetSessionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) DeleteSession(ctx context.Context, in *DeleteSessionReq, opts ...grpc.CallOption) (*DeleteSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResp)
	err := c.cc.Invoke(ctx, Core_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ListUserProfiles(ctx context.Context, in *ListUserProfilesReq, opts ...grpc.CallOption) (*ListUserProfilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserProfilesResp)
	err := c.cc.Invoke(ctx, Core_ListUserProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) ListScenarios(ctx context.Context, in *ListScenariosReq, opts ...grpc.CallOption) (*ListScenariosResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScenariosResp)
	err := c.cc.Invoke(ctx, Core_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServer is the server API for Core service.
// All implementations must embed UnimplementedCoreServer
// for forward compatibility.
type CoreServer interface {
	// User Profile & OSS
	GenerateUploadUrl(context.Context, *GenerateUploadUrlReq) (*GenerateUploadUrlResp, error)
	CreateUserProfile(context.Context, *CreateUserProfileReq) (*CreateUserProfileResp, error)
	GetUserProfile(context.Context, *GetUserProfileReq) (*GetUserProfileResp, error)
	// Scenarios
	CreateScenario(context.Context, *CreateScenarioReq) (*CreateScenarioResp, error)
	GetScenario(context.Context, *GetScenarioReq) (*GetScenarioResp, error)
	// Practice Sessions
	CreateSession(context.Context, *CreateSessionReq) (*CreateSessionResp, error)
	UpdateSessionStatus(context.Context, *UpdateSessionStatusReq) (*UpdateSessionStatusResp, error)
	// Dialogues
	AddDialogue(context.Context, *AddDialogueReq) (*AddDialogueResp, error)
	UpdateDialogueEvaluation(context.Context, *UpdateDialogueEvaluationReq) (*UpdateDialogueEvaluationResp, error)
	// 上下文查询 (供 BFF WebSocket 阶段一次性调用，绕过流式链路)
	GetPracticeContext(context.Context, *GetPracticeContextReq) (*GetPracticeContextResp, error)
	// 列表与详情
	ListSessions(context.Context, *ListSessionsReq) (*ListSessionsResp, error)
	GetSessionDetail(context.Context, *GetSessionDetailReq) (*GetSessionDetailResp, error)
	DeleteSession(context.Context, *DeleteSessionReq) (*DeleteSessionResp, error)
	ListUserProfiles(context.Context, *ListUserProfilesReq) (*ListUserProfilesResp, error)
	ListScenarios(context.Context, *ListScenariosReq) (*ListScenariosResp, error)
	mustEmbedUnimplementedCoreServer()
}

// UnimplementedCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServer struct{}

func (UnimplementedCoreServer) GenerateUploadUrl(context.Context, *GenerateUploadUrlReq) (*GenerateUploadUrlResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateUploadUrl not implemented")
}
func (UnimplementedCoreServer) CreateUserProfile(context.Context, *CreateUserProfileReq) (*CreateUserProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserProfile not implemented")
}
func (UnimplementedCoreServer) GetUserProfile(context.Context, *GetUserProfileReq) (*GetUserProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedCoreServer) CreateScenario(context.Context, *CreateScenarioReq) (*CreateScenarioResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScenario not implemented")
}
func (UnimplementedCoreServer) GetScenario(context.Context, *GetScenarioReq) (*GetScenarioResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScenario not implemented")
}
func (UnimplementedCoreServer) CreateSession(context.Context, *CreateSessionReq) (*CreateSessionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedCoreServer) UpdateSessionStatus(context.Context, *UpdateSessionStatusReq) (*UpdateSessionStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSessionStatus not implemented")
}
func (UnimplementedCoreServer) AddDialogue(context.Context, *AddDialogueReq) (*AddDialogueResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDialogue not implemented")
}
func (UnimplementedCoreServer) UpdateDialogueEvaluation(context.Context, *UpdateDialogueEvaluationReq) (*UpdateDialogueEvaluationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDialogueEvaluation not implemented")
}
func (UnimplementedCoreServer) GetPracticeContext(context.Context, *GetPracticeContextReq) (*GetPracticeContextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPracticeContext not implemented")
}
func (UnimplementedCoreServer) ListSessions(context.Context, *ListSessionsReq) (*ListSessionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedCoreServer) GetSessionDetail(context.Context, *GetSessionDetailReq) (*GetSessionDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionDetail not implemented")
}
func (UnimplementedCoreServer) DeleteSession(context.Context, *DeleteSessionReq) (*DeleteSessionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedCoreServer) ListUserProfiles(context.Context, *ListUserProfilesReq) (*ListUserProfilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserProfiles not implemented")
}
func (UnimplementedCoreServer) ListScenarios(context.Context, *ListScenariosReq) (*ListScenariosResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedCoreServer) mustEmbedUnimplementedCoreServer() {}
func (UnimplementedCoreServer) testEmbeddedByValue()              {}

// UnsafeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServer will
// result in compilation errors.
type UnsafeCoreServer interface {
	mustEmbedUnimplementedCoreServer()
}

func RegisterCoreServer(s grpc.ServiceRegistrar, srv CoreServer) {
	// If the following call panics, it indicates UnimplementedCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Core_ServiceDesc, srv)
}

func _Core_GenerateUploadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUploadUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GenerateUploadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GenerateUploadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GenerateUploadUrl(ctx, req.(*GenerateUploadUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateUserProfile(ctx, req.(*CreateUserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetUserProfile(ctx, req.(*GetUserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScenarioReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateScenario(ctx, req.(*CreateScenarioReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScenarioReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetScenario(ctx, req.(*GetScenarioReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateSession(ctx, req.(*CreateSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpdateSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpdateSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_UpdateSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpdateSessionStatus(ctx, req.(*UpdateSessionStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_AddDialogue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDialogueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).AddDialogue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_AddDialogue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).AddDialogue(ctx, req.(*AddDialogueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpdateDialogueEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDialogueEvaluationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpdateDialogueEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_UpdateDialogueEvaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpdateDialogueEvaluation(ctx, req.(*UpdateDialogueEvaluationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetPracticeContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPracticeContextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetPracticeContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetPracticeContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetPracticeContext(ctx, req.(*GetPracticeContextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ListSessions(ctx, req.(*ListSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetSessionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetSessionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetSessionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetSessionDetail(ctx, req.(*GetSessionDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).DeleteSession(ctx, req.(*DeleteSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ListUserProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserProfilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ListUserProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ListUserProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ListUserProfiles(ctx, req.(*ListUserProfilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ListScenarios(ctx, req.(*ListScenariosReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Core_ServiceDesc is the grpc.ServiceDesc for Core service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Core_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateUploadUrl",
			Handler:    _Core_GenerateUploadUrl_Handler,
		},
		{
			MethodName: "CreateUserProfile",
			Handler:    _Core_CreateUserProfile_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _Core_GetUserProfile_Handler,
		},
		{
			MethodName: "CreateScenario",
			Handler:    _Core_CreateScenario_Handler,
		},
		{
			MethodName: "GetScenario",
			Handler:    _Core_GetScenario_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Core_CreateSession_Handler,
		},
		{
			MethodName: "UpdateSessionStatus",
			Handler:    _Core_UpdateSessionStatus_Handler,
		},
		{
			MethodName: "AddDialogue",
			Handler:    _Core_AddDialogue_Handler,
		},
		{
			MethodName: "UpdateDialogueEvaluation",
			Handler:    _Core_UpdateDialogueEvaluation_Handler,
		},
		{
			MethodName: "GetPracticeContext",
			Handler:    _Core_GetPracticeContext_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Core_ListSessions_Handler,
		},
		{
			MethodName: "GetSessionDetail",
			Handler:    _Core_GetSessionDetail_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _Core_DeleteSession_Handler,
		},
		{
			MethodName: "ListUserProfiles",
			Handler:    _Core_ListUserProfiles_Handler,
		},
		{
			MethodName: "ListScenarios",
			Handler:    _Core_ListScenarios_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
