// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package aiclient

import (
	"context"

	"ai_interview/rpc/ai/ai"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAiCommentaryReq  = ai.GetAiCommentaryReq
	GetAiCommentaryResp = ai.GetAiCommentaryResp
	GetAiSuggestionReq  = ai.GetAiSuggestionReq
	GetAiSuggestionResp = ai.GetAiSuggestionResp
	ParseResumeReq      = ai.ParseResumeReq
	ParseResumeResp     = ai.ParseResumeResp

	Ai interface {
		ParseResume(ctx context.Context, in *ParseResumeReq, opts ...grpc.CallOption) (*ParseResumeResp, error)
		GetAiSuggestion(ctx context.Context, in *GetAiSuggestionReq, opts ...grpc.CallOption) (*GetAiSuggestionResp, error)
		GetAiCommentary(ctx context.Context, in *GetAiCommentaryReq, opts ...grpc.CallOption) (*GetAiCommentaryResp, error)
	}

	defaultAi struct {
		cli zrpc.Client
	}
)

func NewAi(cli zrpc.Client) Ai {
	return &defaultAi{
		cli: cli,
	}
}

func (m *defaultAi) ParseResume(ctx context.Context, in *ParseResumeReq, opts ...grpc.CallOption) (*ParseResumeResp, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.ParseResume(ctx, in, opts...)
}

func (m *defaultAi) GetAiSuggestion(ctx context.Context, in *GetAiSuggestionReq, opts ...grpc.CallOption) (*GetAiSuggestionResp, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.GetAiSuggestion(ctx, in, opts...)
}

func (m *defaultAi) GetAiCommentary(ctx context.Context, in *GetAiCommentaryReq, opts ...grpc.CallOption) (*GetAiCommentaryResp, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.GetAiCommentary(ctx, in, opts...)
}
